/** First-party interface labels only. User content is not a translation source. */
export const APP_JA: Readonly<Record<string, string>> = {
  Access: "アクセス",
  Add: "追加",
  Apply: "適用",
  Approve: "承認",
  "Approve once": "今回のみ承認",
  Archive: "アーカイブ",
  Back: "戻る",
  Browse: "参照",
  Build: "ビルド",
  Cancel: "キャンセル",
  Capture: "撮影",
  Change: "変更",
  Clear: "クリア",
  Close: "閉じる",
  Completed: "完了",
  Configure: "設定",
  Confirm: "確認",
  Connecting: "接続中",
  Copy: "コピー",
  Custom: "カスタム",
  Decline: "拒否",
  Delete: "削除",
  Dismiss: "閉じる",
  Done: "完了",
  Edit: "編集",
  Exit: "終了",
  Expand: "展開",
  Failed: "失敗",
  Favorites: "お気に入り",
  Idle: "アイドル",
  Interrupted: "中断",
  Light: "ライト",
  Dark: "ダーク",
  Loading: "読み込み中",
  Manual: "手動",
  More: "その他",
  Name: "名前",
  Navigate: "移動",
  New: "新規",
  Next: "次へ",
  Off: "オフ",
  Offline: "オフライン",
  On: "オン",
  Open: "開く",
  Pause: "一時停止",
  Pending: "保留中",
  Play: "再生",
  Previous: "前へ",
  Record: "録画",
  Reload: "再読み込み",
  Remove: "削除",
  Rename: "名前を変更",
  Replace: "置き換え",
  Reset: "リセット",
  Resume: "再開",
  Running: "実行中",
  Save: "保存",
  Search: "検索",
  Select: "選択",
  Sending: "送信中",
  Settings: "設定",
  Skip: "スキップ",
  Skipped: "スキップ済み",
  Steer: "方向修正",
  Steering: "方向修正中",
  Stop: "停止",
  Supervised: "監督付き",
  Switch: "切り替え",
  System: "システム",
  Test: "テスト",
  Time: "時刻",
  Unknown: "不明",
  Up: "上へ",
  Waiting: "待機中",
  Working: "作業中",
  Auto: "自動",
  Low: "低",
  Ultra: "最大",
  "Built-in": "内蔵",
  "A calm, dependable home for long coding sessions with your AI agents.":
    "AI エージェントとの長いコーディングセッションに、落ち着いて頼れる居場所を。",
  Sidebar: "サイドバー",
  "Toggle Sidebar": "サイドバーを切り替え",
  "Displays the mobile sidebar.": "モバイル用サイドバーを表示します。",
  "Sidebar options": "サイドバーのオプション",
  "Sidebar image": "サイドバー画像",
  "Branding name": "ブランド名",
  "Accent color": "アクセントカラー",
  "Used for buttons, focus rings, and highlights.":
    "ボタン、フォーカスリング、ハイライトに使います。",
  Theme: "テーマ",
  "Match your system, or pick light or dark.":
    "システム設定に合わせるか、ライトまたはダークを選びます。",
  "Optional — Make it yours": "任意 — 自分好みに設定",
  Projects: "プロジェクト",
  Project: "プロジェクト",
  "Group projects": "プロジェクトをグループ化",
  "Sort projects": "プロジェクトを並べ替え",
  "Sort threads": "スレッドを並べ替え",
  "Visible threads": "表示するスレッド",
  "Visible thread count": "表示スレッド数",
  "Decrease visible thread count": "表示スレッド数を減らす",
  "Increase visible thread count": "表示スレッド数を増やす",
  Messages: "メッセージ",
  Tokens: "トークン",
  Environments: "環境",
  Skills: "スキル",
  Code: "コード",
  Chat: "チャット",
  Files: "ファイル",
  Sources: "ソース",
  Resources: "リソース",
  "Project scripts": "プロジェクトスクリプト",
  "Command palette": "コマンドパレット",
  "Open settings": "設定を開く",
  "Go to threads": "スレッドへ移動",
  "No threads yet": "スレッドはまだありません",
  "Signed in as": "ログイン中:",
  "Add project": "プロジェクトを追加",
  "Project folder": "プロジェクトフォルダー",
  "Project title": "プロジェクト名",
  "Project title cannot be empty": "プロジェクト名は空にできません",
  "Rename project": "プロジェクト名を変更",
  "Failed to rename project": "プロジェクト名を変更できませんでした",
  "Failed to add project": "プロジェクトを追加できませんでした",
  "Select parent folder": "親フォルダーを選択",
  "Browse a folder on disk": "ディスク上のフォルダーを参照",
  "Local folder": "ローカルフォルダー",
  "Primary directory": "プライマリディレクトリ",
  "Additional directories": "追加ディレクトリ",
  "Additional directory path": "追加ディレクトリのパス",
  "No additional directories configured.": "追加ディレクトリは設定されていません。",
  "Enter a workspace path": "ワークスペースのパスを入力",
  "Absolute path": "絶対パス",
  "Relative paths require an active project.":
    "相対パスを使うにはアクティブなプロジェクトが必要です。",
  "Windows-style paths are only supported on Windows.":
    "Windows 形式のパスは Windows でのみ使用できます。",
  "Workspace path": "ワークスペースのパス",
  "Workspace path is unavailable": "ワークスペースのパスを利用できません",
  "Project folder unavailable": "プロジェクトフォルダーを利用できません",
  "Project API unavailable.": "プロジェクト API を利用できません。",
  "Environment API is not available.": "環境 API を利用できません。",
  "No environment is available.": "利用可能な環境がありません。",
  "Unable to browse projects": "プロジェクトを参照できません",
  "Unable to open project": "プロジェクトを開けません",
  "Unable to clone project": "プロジェクトをクローンできません",
  "Clone failed": "クローンに失敗しました",
  "Preparing worktree": "ワークツリーを準備中",
  "Run automatically on worktree creation": "ワークツリー作成時に自動実行",
  "Project is not empty": "プロジェクトは空ではありません",
  "Delete all threads in this project before removing it.":
    "削除する前に、このプロジェクト内のすべてのスレッドを削除してください。",
  "Create another project in this environment before moving this thread.":
    "このスレッドを移動する前に、この環境に別のプロジェクトを作成してください。",
  "Choose another project folder before moving this thread.":
    "このスレッドを移動する前に、別のプロジェクトフォルダーを選択してください。",
  "New thread": "新しいスレッド",
  "New thread in": "新しいスレッドの作成先",
  "New thread in...": "新しいスレッドの作成先...",
  "Thread title cannot be empty": "スレッド名は空にできません",
  "Thread ID copied": "スレッド ID をコピーしました",
  "Failed to copy thread ID": "スレッド ID をコピーできませんでした",
  "Failed to rename thread": "スレッド名を変更できませんでした",
  "Failed to archive thread": "スレッドをアーカイブできませんでした",
  "Move Thread": "スレッドを移動",
  "Destination project folder": "移動先プロジェクトフォルダー",
  "Thread moved": "スレッドを移動しました",
  "Unable to move thread": "スレッドを移動できません",
  "Failed to move thread": "スレッドの移動に失敗しました",
  "No project folder to move to": "移動先のプロジェクトフォルダーがありません",
  "No active thread": "アクティブなスレッドはありません",
  "Pick a thread to continue": "続行するスレッドを選択",
  "Select an existing thread or create a new one to get started.":
    "既存のスレッドを選択するか、新しいスレッドを作成して開始します。",
  "The environment for this thread is not available.": "このスレッドの環境を利用できません。",
  "This thread does not have a workspace path to copy.":
    "このスレッドにはコピーできるワークスペースパスがありません。",
  "This thread does not have a workspace path to save into.":
    "このスレッドには保存先のワークスペースパスがありません。",
  "Repair thread messages": "スレッドメッセージを修復",
  "Unable to repair thread": "スレッドを修復できません",
  "Repair progress": "修復の進行状況",
  Repaired: "修復済み",
  "Cancel turn": "ターンをキャンセル",
  "Stop generation": "生成を停止",
  "Switch response model for this thread": "このスレッドの応答モデルを切り替え",
  "Switch this thread into plan mode": "このスレッドを計画モードに切り替え",
  "Switch this thread back to normal build mode": "このスレッドを通常のビルドモードに戻す",
  "Revert to this message": "このメッセージまで戻す",
  "Copied message": "メッセージをコピーしました",
  "Copy message": "メッセージをコピー",
  "Unable to copy message": "メッセージをコピーできません",
  "Scroll to bottom": "最下部へスクロール",
  "Send message": "メッセージを送信",
  "Send a message to start the conversation.": "メッセージを送信して会話を始めましょう。",
  "Queue message": "メッセージをキューに追加",
  Queued: "キュー済み",
  "Queued message prompt": "キュー済みメッセージのプロンプト",
  "Remove queued message": "キュー済みメッセージを削除",
  "More composer controls": "その他の入力コントロール",
  "Expand composer": "入力欄を展開",
  "Attach files": "ファイルを添付",
  "Attach files after answering plan questions.":
    "計画に関する質問へ回答してからファイルを添付してください。",
  "Draft attachment may not persist": "下書きの添付ファイルが保持されない可能性があります",
  "Copy to clipboard": "クリップボードにコピー",
  "Copied!": "コピーしました！",
  "Failed to copy": "コピーに失敗しました",
  "Copy full path": "フルパスをコピー",
  "Copy relative path": "相対パスをコピー",
  "Failed to copy path": "パスをコピーできませんでした",
  "Path copied": "パスをコピーしました",
  "Path unavailable": "パスを利用できません",
  "Open in editor": "エディターで開く",
  "Open in editor is unavailable": "エディターで開く機能を利用できません",
  "No installed editors found": "インストール済みエディターが見つかりません",
  "Unable to open file": "ファイルを開けません",
  "Link opening is unavailable.": "リンクを開く機能を利用できません。",
  Provider: "プロバイダー",
  Model: "モデル",
  Reasoning: "推論",
  "New model": "新しいモデル",
  "Use global default": "グローバル既定値を使用",
  "Search models...": "モデルを検索...",
  "No models found": "モデルが見つかりません",
  "Connect a provider": "プロバイダーを接続",
  "Complete the login in the window that opened, then refresh status.":
    "開いたウィンドウでログインを完了し、状態を更新してください。",
  "Log in by running:": "次を実行してログイン:",
  "Ask before edits and commands.": "編集とコマンドの前に確認します。",
  "Ask before commands and file changes.": "コマンドとファイル変更の前に確認します。",
  "Apply edits automatically and ask before other actions.":
    "編集は自動で適用し、その他の操作は事前に確認します。",
  "Auto-accept edits": "編集を自動承認",
  "Auto-approve edits, ask before other actions.":
    "編集は自動承認し、その他の操作は事前に確認します。",
  "Allow commands and edits without prompts.": "確認なしでコマンドと編集を許可します。",
  "Bypass permissions": "権限確認を省略",
  "Full access": "フルアクセス",
  "Run without permission checks. Use only in an isolated environment.":
    "権限確認なしで実行します。隔離された環境でのみ使用してください。",
  "Run autonomously with Claude's background safety classifier.":
    "Claude のバックグラウンド安全分類を使って自律実行します。",
  "Always allow this session": "このセッションでは常に許可",
  "PENDING APPROVAL": "承認待ち",
  "Research and propose changes without editing files.":
    "ファイルを編集せず、調査して変更案を提示します。",
  Mode: "モード",
  "No limit": "上限なし",
  Limits: "上限",
  "Token budget": "トークン予算",
  Budget: "予算",
  Objective: "目標",
  "View or update the Codex goal": "Codex の目標を表示または更新",
  "Replace the active goal?": "現在の目標を置き換えますか？",
  "The existing unfinished goal will be replaced.": "既存の未完了目標は置き換えられます。",
  "Already complete": "すでに完了",
  "No active plan": "アクティブな計画はありません",
  "No active plan yet.": "まだアクティブな計画はありません。",
  Plan: "計画",
  "Plan actions": "計画の操作",
  "Plan ready": "計画の準備完了",
  "Review the plan": "計画を確認",
  "Save plan to workspace": "計画をワークスペースに保存",
  "Save to workspace": "ワークスペースに保存",
  "Plan saved": "計画を保存しました",
  "Plan saved to workspace": "計画をワークスペースに保存しました",
  "Plans will appear here when generated.": "生成された計画はここに表示されます。",
  "Could not copy plan": "計画をコピーできませんでした",
  "Could not save plan": "計画を保存できませんでした",
  "Implementation actions": "実装操作",
  "Implement in a new thread": "新しいスレッドで実装",
  "Could not start implementation thread": "実装スレッドを開始できませんでした",
  Steps: "手順",
  "Follow-up steering into active turn": "実行中ターンへのフォローアップ方向修正",
  "Follow-up accepted for the active turn; waiting for the provider to act on it.":
    "実行中ターンへのフォローアップを受け付けました。プロバイダーの処理を待っています。",
  "Waiting for compact": "圧縮完了を待機中",
  "No Git": "Git なし",
  Page: "ページ",
  "Connecting to workspace": "ワークスペースに接続中",
  "Waiting for network.": "ネットワークを待っています。",
  "Validating the pairing link and preparing your session.":
    "ペアリングリンクを検証し、セッションを準備しています。",
  "Pair with this environment": "この環境とペアリング",
  "Pairing with this environment": "この環境とペアリング中",
  "Pairing token": "ペアリングトークン",
  "Paste a one-time token or pairing secret":
    "一度限りのトークンまたはペアリングシークレットを貼り付け",
  "Admin password": "管理者パスワード",
  Password: "パスワード",
  "Enter the admin password": "管理者パスワードを入力",
  Disconnected: "切断済み",
  "Reconnecting…": "再接続中…",
  "Client and server versions differ": "クライアントとサーバーのバージョンが異なります",
  "Dismiss version mismatch warning": "バージョン不一致の警告を閉じる",
  "Update available": "更新があります",
  "Update downloaded": "更新をダウンロードしました",
  "Restart to update": "再起動して更新",
  "Restart the app from the update button to install it.":
    "更新ボタンからアプリを再起動してインストールしてください。",
  "Could not start update download": "更新のダウンロードを開始できませんでした",
  "Could not download update": "更新をダウンロードできませんでした",
  "Could not install update": "更新をインストールできませんでした",
  "Could not open release": "リリースを開けませんでした",
  "Dismiss update": "更新通知を閉じる",
  "View macOS update": "macOS 版の更新を表示",
  "Intel build on Apple Silicon": "Apple Silicon 上の Intel ビルド",
  "Reload app": "アプリを再読み込み",
  "Dismiss error": "エラーを閉じる",
  "Dismiss notification": "通知を閉じる",
  "Dismiss provider status": "プロバイダー状態を閉じる",
  "Dismiss provider update notice": "プロバイダー更新通知を閉じる",
  "Dismiss until next launch": "次回起動まで閉じる",
  "Dismiss until provider status changes": "プロバイダー状態が変わるまで閉じる",
  "Copy error": "エラーをコピー",
  "Copy command": "コマンドをコピー",
  "Unable to run command": "コマンドを実行できません",
  "Repository lookup failed": "リポジトリの検索に失敗しました",
  "Unable to open pull request link": "プルリクエストのリンクを開けません",
  "Working for": "作業時間",
  "Daily generating time for the last few months; brighter cells mean more time.":
    "過去数か月の日別生成時間です。明るいセルほど時間が長いことを示します。",
  "Loading work log...": "作業ログを読み込み中...",
  "Actions are project-scoped commands you can run from the top bar or keybindings.":
    "アクションはプロジェクト単位のコマンドで、トップバーまたはキーバインドから実行できます。",
  "Script actions": "スクリプト操作",
  "Subscription actions": "サブスクリプション操作",
  "Upstream checks": "アップストリーム確認",
  "Local checks": "ローカル確認",
  "Add action": "アクションを追加",
  "Delete action": "アクションを削除",
  "Run on": "実行タイミング",
  "Grouping rule": "グループ化ルール",
  "Project grouping": "プロジェクトのグループ化",
  "Project grouping rule": "プロジェクトのグループ化ルール",
  "Choose icon": "アイコンを選択",
  "Press shortcut": "ショートカットを押してください",
  Keybinding: "キーバインド",
  "This action cannot be undone.": "この操作は取り消せません。",
};
