/**
 * Exact English-to-Japanese translations for first-party application chrome.
 *
 * Dynamic transcript text, operator input, provider output, paths, file names,
 * and repository content must not be translated through this catalog.
 */
export const APP_JA: Readonly<Record<string, string>> = {
  // Common actions and status
  Access: "アクセス",
  Add: "追加",
  Apply: "適用",
  Approve: "承認",
  "Approve once": "今回のみ承認",
  Archive: "アーカイブ",
  Back: "戻る",
  Browse: "参照",
  Build: "ビルド",
  Cancel: "キャンセル",
  Capture: "撮影",
  Change: "変更",
  Clear: "クリア",
  Close: "閉じる",
  Completed: "完了",
  Configure: "設定",
  Confirm: "確認",
  Connecting: "接続中",
  Conservative: "慎重",
  Copy: "コピー",
  Custom: "カスタム",
  Decline: "拒否",
  Delete: "削除",
  Dismiss: "閉じる",
  Done: "完了",
  Edit: "編集",
  Exit: "終了",
  Expand: "展開",
  Failed: "失敗",
  Favorites: "お気に入り",
  Idle: "アイドル",
  Interrupted: "中断",
  Light: "ライト",
  Dark: "ダーク",
  Loading: "読み込み中",
  Manual: "手動",
  More: "その他",
  Name: "名前",
  Navigate: "移動",
  New: "新規",
  Next: "次へ",
  Off: "オフ",
  Offline: "オフライン",
  On: "オン",
  Open: "開く",
  Pause: "一時停止",
  Pending: "保留中",
  Play: "再生",
  Previous: "前へ",
  Record: "録画",
  Reload: "再読み込み",
  Remove: "削除",
  Rename: "名前を変更",
  Replace: "置き換え",
  Reset: "リセット",
  Resume: "再開",
  Retake: "撮り直す",
  Running: "実行中",
  Save: "保存",
  Search: "検索",
  Select: "選択",
  Sending: "送信中",
  Settings: "設定",
  Skip: "スキップ",
  Skipped: "スキップ済み",
  Steer: "方向修正",
  Steering: "方向修正中",
  Stop: "停止",
  Supervised: "監督付き",
  Switch: "切り替え",
  System: "システム",
  Test: "テスト",
  Time: "時刻",
  Unknown: "不明",
  Up: "上へ",
  Waiting: "待機中",
  Working: "作業中",
  Auto: "自動",
  Balanced: "バランス",
  Broad: "広範囲",
  Low: "低",
  Tight: "限定",
  Ultra: "最大",
  "Built-in": "内蔵",

  // Application shell and sidebar
  "A calm, dependable home for long coding sessions with your AI agents.":
    "AI エージェントとの長いコーディングセッションに、落ち着いて頼れる居場所を。",
  "Club Code splash screen": "Club Code スプラッシュ画面",
  "Club Code on GitHub": "GitHub の Club Code",
  Sidebar: "サイドバー",
  "Toggle Sidebar": "サイドバーを切り替え",
  "Displays the mobile sidebar.": "モバイル用サイドバーを表示します。",
  "Sidebar options": "サイドバーのオプション",
  "Sidebar image": "サイドバー画像",
  "Branding name": "ブランド名",
  "Accent color": "アクセントカラー",
  "Used for buttons, focus rings, and highlights.":
    "ボタン、フォーカスリング、ハイライトに使います。",
  Theme: "テーマ",
  "Match your system, or pick light or dark.":
    "システム設定に合わせるか、ライトまたはダークを選びます。",
  "Optional — Make it yours": "任意 — 自分好みに設定",
  Projects: "プロジェクト",
  Project: "プロジェクト",
  "Group projects": "プロジェクトをグループ化",
  "Sort projects": "プロジェクトを並べ替え",
  "Sort threads": "スレッドを並べ替え",
  "Visible threads": "表示するスレッド",
  "Visible thread count": "表示スレッド数",
  "Decrease visible thread count": "表示スレッド数を減らす",
  "Increase visible thread count": "表示スレッド数を増やす",
  Messages: "メッセージ",
  Tokens: "トークン",
  Environments: "環境",
  Skills: "スキル",
  Code: "コード",
  Chat: "チャット",
  Files: "ファイル",
  Sources: "ソース",
  Resources: "リソース",
  "Project scripts": "プロジェクトスクリプト",
  "Command palette": "コマンドパレット",
  "Open settings": "設定を開く",
  "Go to threads": "スレッドへ移動",
  "No threads yet": "スレッドはまだありません",
  "No recent activity": "最近のアクティビティはありません",
  "Recent activity": "最近のアクティビティ",
  "Last activity:": "最終アクティビティ:",
  "Current activity:": "現在のアクティビティ:",
  "Signed in as": "ログイン中:",

  // Projects, environments, and folders
  "Add project": "プロジェクトを追加",
  "Project folder": "プロジェクトフォルダー",
  "Project title": "プロジェクト名",
  "Project title cannot be empty": "プロジェクト名は空にできません",
  "Rename project": "プロジェクト名を変更",
  "Failed to rename project": "プロジェクト名を変更できませんでした",
  "Failed to add project": "プロジェクトを追加できませんでした",
  "Select parent folder": "親フォルダーを選択",
  "Browse a folder on disk": "ディスク上のフォルダーを参照",
  "Local folder": "ローカルフォルダー",
  "Local environment": "ローカル環境",
  "Primary directory": "プライマリディレクトリ",
  "Additional directories": "追加ディレクトリ",
  "Additional directory path": "追加ディレクトリのパス",
  "No additional directories configured.": "追加ディレクトリは設定されていません。",
  "Enter a workspace path": "ワークスペースのパスを入力",
  "Absolute path": "絶対パス",
  "Relative paths require an active project.":
    "相対パスを使うにはアクティブなプロジェクトが必要です。",
  "Windows-style paths are only supported on Windows.":
    "Windows 形式のパスは Windows でのみ使用できます。",
  "Workspace path": "ワークスペースのパス",
  "Workspace path is unavailable": "ワークスペースのパスを利用できません",
  "Project folder unavailable": "プロジェクトフォルダーを利用できません",
  "Project API unavailable.": "プロジェクト API を利用できません。",
  "Environment API is not available.": "環境 API を利用できません。",
  "No environment is available.": "利用可能な環境がありません。",
  "Unable to browse projects": "プロジェクトを参照できません",
  "Unable to open project": "プロジェクトを開けません",
  "Unable to clone project": "プロジェクトをクローンできません",
  "Clone failed": "クローンに失敗しました",
  "Preparing worktree": "ワークツリーを準備中",
  "Run automatically on worktree creation": "ワークツリー作成時に自動実行",
  "Project is not empty": "プロジェクトは空ではありません",
  "Delete all threads in this project before removing it.":
    "削除する前に、このプロジェクト内のすべてのスレッドを削除してください。",
  "Create another project in this environment before moving this thread.":
    "このスレッドを移動する前に、この環境に別のプロジェクトを作成してください。",
  "Choose another project folder before moving this thread.":
    "このスレッドを移動する前に、別のプロジェクトフォルダーを選択してください。",
  "Project hidden for meeting privacy": "ミーティングプライバシーによりプロジェクトを非表示",
  "Open the Meeting Privacy manager to reveal this existing folder.":
    "この既存フォルダーを表示するには、ミーティングプライバシー管理を開いてください。",
  "Meeting privacy": "ミーティングプライバシー",
  "Meeting privacy on": "ミーティングプライバシー: オン",
  "Manage meeting privacy": "ミーティングプライバシーを管理",
  Unhide: "再表示",
  "Unhide all": "すべて再表示",

  // Threads and thread actions
  "New thread": "新しいスレッド",
  "New thread in": "新しいスレッドの作成先",
  "New thread in...": "新しいスレッドの作成先...",
  "Thread details": "スレッドの詳細",
  "Thread title cannot be empty": "スレッド名は空にできません",
  "Thread ID copied": "スレッド ID をコピーしました",
  "Failed to copy thread ID": "スレッド ID をコピーできませんでした",
  "Failed to rename thread": "スレッド名を変更できませんでした",
  "Failed to archive thread": "スレッドをアーカイブできませんでした",
  "Unable to duplicate thread": "スレッドを複製できません",
  "Failed to duplicate thread": "スレッドの複製に失敗しました",
  "Move Thread": "スレッドを移動",
  "Destination project folder": "移動先プロジェクトフォルダー",
  "Thread moved": "スレッドを移動しました",
  "Unable to move thread": "スレッドを移動できません",
  "Failed to move thread": "スレッドの移動に失敗しました",
  "No project folder to move to": "移動先のプロジェクトフォルダーがありません",
  "No active thread": "アクティブなスレッドはありません",
  "Pick a thread to continue": "続行するスレッドを選択",
  "Select an existing thread or create a new one to get started.":
    "既存のスレッドを選択するか、新しいスレッドを作成して開始します。",
  "The environment for this thread is not available.": "このスレッドの環境を利用できません。",
  "This thread's environment is not connected.": "このスレッドの環境は接続されていません。",
  "This thread does not have a workspace path to copy.":
    "このスレッドにはコピーできるワークスペースパスがありません。",
  "This thread does not have a workspace path to save into.":
    "このスレッドには保存先のワークスペースパスがありません。",
  "Repair thread messages": "スレッドメッセージを修復",
  "Unable to repair thread": "スレッドを修復できません",
  "Repair progress": "修復の進行状況",
  Repaired: "修復済み",
  "Cancel turn": "ターンをキャンセル",
  "Stop generation": "生成を停止",
  "Could not stop this thread": "このスレッドを停止できませんでした",
  "Switch response model for this thread": "このスレッドの応答モデルを切り替え",
  "Switch this thread into plan mode": "このスレッドを計画モードに切り替え",
  "Switch this thread back to normal build mode": "このスレッドを通常のビルドモードに戻す",
  "Revert to this message": "このメッセージまで戻す",
  "Copied message": "メッセージをコピーしました",
  "Copy message": "メッセージをコピー",
  "Unable to copy message": "メッセージをコピーできません",
  "Scroll to bottom": "最下部へスクロール",

  // Composer, attachments, and message controls
  "Send message": "メッセージを送信",
  "Send a message to start the conversation.": "メッセージを送信して会話を始めましょう。",
  "Tell Club Code what to change": "Club Code に変更内容を伝える",
  "Queue message": "メッセージをキューに追加",
  Queued: "キュー済み",
  "Queued message prompt": "キュー済みメッセージのプロンプト",
  "Remove queued message": "キュー済みメッセージを削除",
  "One-time text to enter": "今回のみ入力するテキスト",
  "The current draft is already at the message size limit.":
    "現在の下書きはすでにメッセージサイズの上限です。",
  "More composer controls": "その他の入力コントロール",
  "Expand composer": "入力欄を展開",
  "Also adjust the related composer controls.": "関連する入力コントロールも調整します。",
  "Attach files": "ファイルを添付",
  "Attach files after answering plan questions.":
    "計画に関する質問へ回答してからファイルを添付してください。",
  "Add to one-time chat context": "今回のみのチャットコンテキストに追加",
  "Some files were not added": "一部のファイルを追加できませんでした",
  "Draft attachment may not persist": "下書きの添付ファイルが保持されない可能性があります",
  "The file contents are visible in the composer and will be sent as text.":
    "ファイル内容は入力欄に表示され、テキストとして送信されます。",
  "File content is capped for display.": "表示するファイル内容には上限があります。",
  "This directory is capped for safe display.":
    "安全な表示のため、このディレクトリの内容には上限があります。",
  "Hidden and credential-like paths are omitted.": "隠しパスと認証情報に見えるパスは省略されます。",
  "Change summary capped at 200 lines.": "変更の概要は 200 行までです。",
  "Copy to clipboard": "クリップボードにコピー",
  "Copied!": "コピーしました！",
  "Failed to copy": "コピーに失敗しました",
  "Clipboard API unavailable.": "クリップボード API を利用できません。",
  "Copy full path": "フルパスをコピー",
  "Copy relative path": "相対パスをコピー",
  "Failed to copy path": "パスをコピーできませんでした",
  "Path copied": "パスをコピーしました",
  "Path unavailable": "パスを利用できません",
  "Open in editor": "エディターで開く",
  "Open in editor is unavailable": "エディターで開く機能を利用できません",
  "No installed editors found": "インストール済みエディターが見つかりません",
  "Unable to open file": "ファイルを開けません",
  "Link opening is unavailable.": "リンクを開く機能を利用できません。",

  // Models, providers, modes, and permissions
  Provider: "プロバイダー",
  Model: "モデル",
  Reasoning: "推論",
  "New model": "新しいモデル",
  "Use global default": "グローバル既定値を使用",
  "Search models...": "モデルを検索...",
  "No models found": "モデルが見つかりません",
  "No ready models": "使用可能なモデルがありません",
  "No provider instances are configured.": "プロバイダーインスタンスが設定されていません。",
  "Connect a provider": "プロバイダーを接続",
  "Complete the login in the window that opened, then refresh status.":
    "開いたウィンドウでログインを完了し、状態を更新してください。",
  "Log in by running:": "次を実行してログイン:",
  "Claude permission mode": "Claude 権限モード",
  "Ask before edits and commands.": "編集とコマンドの前に確認します。",
  "Ask before commands and file changes.": "コマンドとファイル変更の前に確認します。",
  "Apply edits automatically and ask before other actions.":
    "編集は自動で適用し、その他の操作は事前に確認します。",
  "Auto-accept edits": "編集を自動承認",
  "Auto-approve edits, ask before other actions.":
    "編集は自動承認し、その他の操作は事前に確認します。",
  "Allow commands and edits without prompts.": "確認なしでコマンドと編集を許可します。",
  "Bypass permissions": "権限確認を省略",
  "Full access": "フルアクセス",
  "Run without permission checks. Use only in an isolated environment.":
    "権限確認なしで実行します。隔離された環境でのみ使用してください。",
  "Run autonomously with Claude's background safety classifier.":
    "Claude のバックグラウンド安全分類を使って自律実行します。",
  "Always allow this session": "このセッションでは常に許可",
  "Grant 5 minutes": "5 分間許可",
  "PENDING APPROVAL": "承認待ち",
  "Favor reliability and low-risk changes.": "信頼性と低リスクの変更を優先します。",
  "Mix quick wins with one structural improvement.":
    "短時間で得られる改善と、1つの構造的改善を組み合わせます。",
  "Research and propose changes without editing files.":
    "ファイルを編集せず、調査して変更案を提示します。",
  "Fast Mode": "高速モード",
  "Runtime mode": "ランタイムモード",
  Mode: "モード",
  "No limit": "上限なし",
  Limits: "上限",
  "Token budget": "トークン予算",
  Budget: "予算",
  Objective: "目標",
  "View or update the Codex goal": "Codex の目標を表示または更新",
  "Replace the active goal?": "現在の目標を置き換えますか？",
  "The existing unfinished goal will be replaced.": "既存の未完了目標は置き換えられます。",
  "Already complete": "すでに完了",
  "No active plan": "アクティブな計画はありません",
  "No active plan yet.": "まだアクティブな計画はありません。",

  // Plan and workflow panels
  Plan: "計画",
  "Current plan": "現在の計画",
  "Plan actions": "計画の操作",
  "Plan ready": "計画の準備完了",
  "Review the plan": "計画を確認",
  "Save plan to workspace": "計画をワークスペースに保存",
  "Save to workspace": "ワークスペースに保存",
  "Plan saved": "計画を保存しました",
  "Plan saved to workspace": "計画をワークスペースに保存しました",
  "Plans will appear here when generated.": "生成された計画はここに表示されます。",
  "Could not copy plan": "計画をコピーできませんでした",
  "Could not save plan": "計画を保存できませんでした",
  "Implementation actions": "実装操作",
  "Implement in a new thread": "新しいスレッドで実装",
  "Could not start implementation thread": "実装スレッドを開始できませんでした",
  Steps: "手順",
  "Agents and tasks": "エージェントとタスク",
  "All agents": "すべてのエージェント",
  "Provider-reported workflow": "プロバイダー報告のワークフロー",
  "Provider-reported workflow graph": "プロバイダー報告のワークフローグラフ",
  "Accessible provider-reported workflow relationships":
    "アクセス可能なプロバイダー報告ワークフロー関係",
  "Recent provider-reported workflow activity": "最近のプロバイダー報告ワークフロー活動",
  "Selected workflow node details": "選択したワークフローノードの詳細",
  "This provider has not reported a safe sub-agent lifecycle for the current turn.":
    "このプロバイダーは現在のターンについて安全なサブエージェントのライフサイクルを報告していません。",
  "Edges appear only for provider-reported parent relationships. Drag the background to pan.":
    "エッジはプロバイダーが報告した親子関係にのみ表示されます。背景をドラッグして移動できます。",
  "Workflow graph viewport controls": "ワークフローグラフの表示操作",
  "Reset workflow graph viewport": "ワークフローグラフ表示をリセット",
  "Zoom workflow graph in": "ワークフローグラフを拡大",
  "Zoom workflow graph out": "ワークフローグラフを縮小",
  "Close Plan and Workflow panel": "計画・ワークフローパネルを閉じる",

  // Auto Nudge and Idle Thread Guard chrome
  "Collapse Auto Nudge controls": "Auto Nudge コントロールを折りたたむ",
  "Expand Auto Nudge controls": "Auto Nudge コントロールを展開",
  "Collapse Idle Thread Guard controls": "Idle Thread Guard コントロールを折りたたむ",
  "Expand Idle Thread Guard controls": "Idle Thread Guard コントロールを展開",
  "Auto Nudge remains stopped": "Auto Nudge は停止したままです",
  "Auto Nudge was not dispatched": "Auto Nudge は送信されませんでした",
  "Failed to save Auto Nudge": "Auto Nudge を保存できませんでした",
  "Offline Auto Nudge environment": "Auto Nudge の環境がオフラインです",
  "This thread was not enabled because the durable Emergency Stop barrier is active.":
    "永続的な緊急停止バリアが有効なため、このスレッドは有効になりませんでした。",
  "This thread changed or became unavailable. Its previous Auto Nudge settings remain in effect.":
    "このスレッドが変更されたか利用不能になりました。以前の Auto Nudge 設定は引き続き有効です。",
  "This thread's saved authority changed or the environment became unavailable.":
    "このスレッドに保存された権限が変更されたか、環境が利用不能になりました。",
  "Still stopping Auto Nudge threads": "Auto Nudge スレッドを引き続き停止中",
  "Background continuation cannot be enabled until every known thread is confirmed Off.":
    "既知のすべてのスレッドがオフと確認されるまで、バックグラウンド継続を有効にできません。",
  "Allow Auto Nudge again only after every known thread has been confirmed Off.":
    "既知のすべてのスレッドがオフと確認された後にのみ、Auto Nudge を再び許可してください。",
  "Emergency Stop all is active": "すべての緊急停止が有効です",
  "Revoke now": "今すぐ取り消す",
  "The exact-thread Stop was not acknowledged. Retry when this environment is connected, or use Emergency Stop all.":
    "対象スレッドの停止が確認されませんでした。環境が接続されたら再試行するか、すべてを緊急停止してください。",
  "The durable Emergency Stop barrier could not be cleared safely. Retry after checking this device's storage and thread connections.":
    "永続的な緊急停止バリアを安全に解除できませんでした。このデバイスのストレージとスレッド接続を確認してから再試行してください。",
  "Follow-up steering into active turn": "実行中ターンへのフォローアップ方向修正",
  "Follow-up accepted for the active turn; waiting for the provider to act on it.":
    "実行中ターンへのフォローアップを受け付けました。プロバイダーの処理を待っています。",
  "Codex is compacting the active turn; Club Code will retry this steer automatically when compaction finishes.":
    "Codex が実行中ターンを圧縮しています。圧縮完了後、Club Code がこの方向修正を自動的に再試行します。",
  "Codex is reviewing the active turn; Club Code will send this follow-up automatically when the active turn is ready.":
    "Codex が実行中ターンを確認しています。ターンの準備ができると Club Code がこのフォローアップを自動送信します。",
  "Waiting for compact": "圧縮完了を待機中",

  // Workspace Observatory and project resources
  "Workspace Observatory": "ワークスペース観測",
  "Close Workspace Observatory": "ワークスペース観測を閉じる",
  "Observe workspace": "ワークスペースを観測",
  "Observatory panes": "観測ペイン",
  "Add observatory pane": "観測ペインを追加",
  "Tiled observatory panes": "並べた観測ペイン",
  "Select this pane, then choose a file or database table.":
    "このペインを選択してから、ファイルまたはデータベーステーブルを選んでください。",
  "Workspace files": "ワークスペースファイル",
  "Latest file line changes": "最新のファイル行変更",
  Databases: "データベース",
  "Read-only databases": "読み取り専用データベース",
  "Finding SQLite databases…": "SQLite データベースを検索中…",
  "Latest database row changes": "最新のデータベース行変更",
  "Rows are capped for safe display.": "安全な表示のため、行数には上限があります。",
  "Project resources": "プロジェクトリソース",
  "Expand Resources": "リソースを展開",
  "Move project resource graphs": "プロジェクトリソースグラフを移動",
  "Resize project resource graphs": "プロジェクトリソースグラフのサイズを変更",
  "Collapse project resource graphs": "プロジェクトリソースグラフを折りたたむ",
  "Collapse resource graphs and stop polling": "リソースグラフを折りたたみ、ポーリングを停止",
  "Hide unavailable graphs": "利用不能なグラフを非表示",
  "Hide unavailable resource graphs": "利用不能なリソースグラフを非表示",
  "Remove sensor cards whose current reading is unavailable.":
    "現在の測定値を利用できないセンサーカードを除外します。",
  "Hardware temperatures": "ハードウェア温度",
  "CPU temp": "CPU 温度",
  "RAM temp": "RAM 温度",
  "GPU temp": "GPU 温度",
  "VRAM temp": "VRAM 温度",
  "Disk temp": "ディスク温度",
  "Other temp": "その他の温度",
  "Measured host sensor temperature only; unavailable values are never estimated.":
    "ホストのセンサーで測定した温度のみを表示します。利用不能な値は推定しません。",
  "Selected project system telemetry": "選択したプロジェクトのシステムテレメトリ",
  "Live refresh cadence": "ライブ更新間隔",
  "Show live line changes": "行の変更をリアルタイム表示",
  "Current changes": "現在の変更",
  "Checking your current changes": "現在の変更を確認中",
  "Checking your changes...": "変更を確認中...",
  "Fresh diff coming up": "最新の差分を準備中",
  "Loading diff viewer...": "差分ビューアーを読み込み中...",
  "Current changes are unavailable because this project is not a git repository.":
    "このプロジェクトは Git リポジトリではないため、現在の変更を利用できません。",
  "Select a thread to inspect current changes.": "現在の変更を確認するスレッドを選択してください。",
  "Split diff view": "差分を左右に表示",
  "Stacked diff view": "差分を上下に表示",
  "Toggle diff panel": "差分パネルを切り替え",
  "No Git": "Git なし",

  // Isolated browser, OCR, and camera
  "Isolated browser workspace": "隔離ブラウザーワークスペース",
  "Open isolated browser": "隔離ブラウザーを開く",
  "Close isolated browser": "隔離ブラウザーを閉じる",
  "Opening isolated browser…": "隔離ブラウザーを起動中…",
  "Open pages, click around, and inspect web apps.":
    "ページを開き、操作し、Web アプリを調査します。",
  "Temporary session · no Node.js · downloads and popups blocked":
    "一時セッション · Node.js なし · ダウンロードとポップアップをブロック",
  "Browser address": "ブラウザーのアドレス",
  "Go back": "戻る",
  "Go forward": "進む",
  Page: "ページ",
  "Page snapshot": "ページスナップショット",
  "One-time browser context · not saved": "今回のみのブラウザーコンテキスト · 保存されません",
  "One-time browser context added": "今回のみのブラウザーコンテキストを追加しました",
  "Browser snapshot not added": "ブラウザースナップショットを追加しませんでした",
  "Finish the current approval or question before adding browser context.":
    "ブラウザーコンテキストを追加する前に、現在の承認または質問を完了してください。",
  "Runs bounded offline OCR on only the currently visible isolated-browser viewport.":
    "現在表示中の隔離ブラウザー領域だけに、範囲を限定したオフライン OCR を実行します。",
  "OCR language": "OCR 言語",
  "Packaged offline OCR language": "同梱オフライン OCR の言語",
  "English OCR": "英語 OCR",
  "Japanese OCR": "日本語 OCR",
  "Visible image text": "表示画像内のテキスト",
  "Copy OCR": "OCR をコピー",
  "Copy the redacted OCR preview": "機密情報を除去した OCR プレビューをコピー",
  "Credential-like assignments or private keys were redacted.":
    "認証情報に見える代入値または秘密鍵は除去されました。",
  "Open camera": "カメラを開く",
  "System camera": "システムカメラ",
  "Camera preview": "カメラプレビュー",
  "Preview the camera, capture a photo, then choose whether to attach it.":
    "カメラをプレビューして写真を撮影し、添付するか選びます。",
  "Take a photo": "写真を撮る",
  "Use photo": "写真を使用",
  "Switch front or rear camera": "前面・背面カメラを切り替え",

  // Ambient overlays and media chrome
  "Ambient image": "アンビエント画像",
  "Ambient streaming player": "アンビエントストリーミングプレイヤー",
  "Ambient YouTube video player": "アンビエント YouTube 動画プレイヤー",
  "Atmosphere console": "アンビエンスコンソール",
  "Open atmosphere console": "アンビエンスコンソールを開く",
  "Close atmosphere console": "アンビエンスコンソールを閉じる",
  "Move atmosphere console": "アンビエンスコンソールを移動",
  "Resize atmosphere console": "アンビエンスコンソールのサイズを変更",
  "Console position": "コンソール位置",
  "Atmosphere command interpreter": "アンビエンスコマンド解釈器",
  "Atmosphere interpreter model": "アンビエンス解釈モデル",
  Interpreter: "解釈器",
  "Local parser · zero tokens": "ローカルパーサー · トークン消費なし",
  "Codex · lightweight first": "Codex · 軽量モデル優先",
  "LM Studio · local": "LM Studio · ローカル",
  "Move ambient image; use arrow keys for precise movement":
    "アンビエント画像を移動。矢印キーで精密に移動できます",
  "Resize ambient image; use arrow keys for precise resizing":
    "アンビエント画像のサイズを変更。矢印キーで精密に調整できます",
  "Disable ambient image": "アンビエント画像を無効化",
  "Previous ambient image": "前のアンビエント画像",
  "Next ambient image": "次のアンビエント画像",
  "Move ambient video": "アンビエント動画を移動",
  "Resize ambient video": "アンビエント動画のサイズを変更",
  "Disable ambient video": "アンビエント動画を無効化",
  "Local media player": "ローカルメディアプレイヤー",
  "Move local media; use arrow keys for precise movement":
    "ローカルメディアを移動。矢印キーで精密に移動できます",
  "Resize local media; use arrow keys for precise resizing":
    "ローカルメディアのサイズを変更。矢印キーで精密に調整できます",
  "Clear local media": "ローカルメディアをクリア",
  "Previous local media": "前のローカルメディア",
  "Next local media": "次のローカルメディア",
  "Toggle local media audio visualizer": "ローカルメディアのオーディオビジュアライザーを切り替え",
  Visualizer: "ビジュアライザー",
  "MilkDrop visualization controls": "MilkDrop ビジュアライザー操作",
  "Previous MilkDrop preset": "前の MilkDrop プリセット",
  "Next MilkDrop preset": "次の MilkDrop プリセット",
  "Random MilkDrop preset": "ランダムな MilkDrop プリセット",
  "Local Media Cinema needs more window space; using the floating layout.":
    "ローカルメディアのシネマ表示にはより広いウィンドウが必要なため、フローティング表示を使います。",
  "Exit local media presentation": "ローカルメディア表示を終了",
  "Local video background": "ローカル動画背景",
  "Local video background controls": "ローカル動画背景の操作",
  "Clear local video background": "ローカル動画背景をクリア",
  "Disable video": "動画を無効化",
  "Previous local video background": "前のローカル動画背景",
  "Next local video background": "次のローカル動画背景",
  "World clock": "世界時計",
  "Move world clock; use arrow keys, or Shift plus arrows for fine movement":
    "世界時計を移動。矢印キー、または Shift + 矢印キーで細かく移動できます",
  "Resize world clock; use arrow keys, or Shift plus arrows for fine resizing":
    "世界時計のサイズを変更。矢印キー、または Shift + 矢印キーで細かく調整できます",
  "Drag to move · Arrow keys move precisely": "ドラッグで移動 · 矢印キーで精密移動",
  "Drag to resize · Arrow keys resize precisely": "ドラッグでサイズ変更 · 矢印キーで精密調整",
  "Drag to move. Arrow keys move by 8 pixels; Shift+Arrow moves by 1.":
    "ドラッグで移動します。矢印キーは 8 ピクセル、Shift + 矢印キーは 1 ピクセル移動します。",
  "Drag to resize. Arrow keys resize by 8 pixels; Shift+Arrow resizes by 1.":
    "ドラッグでサイズ変更します。矢印キーは 8 ピクセル、Shift + 矢印キーは 1 ピクセル調整します。",
  "YouTube playlist controls": "YouTube プレイリスト操作",
  "YouTube URL queue controls": "YouTube URL キュー操作",
  "Previous YouTube playlist item": "前の YouTube プレイリスト項目",
  "Next YouTube playlist item": "次の YouTube プレイリスト項目",
  "Previous YouTube URL": "前の YouTube URL",
  "Next YouTube URL": "次の YouTube URL",
  "Clear YouTube URL queue": "YouTube URL キューをクリア",
  "Clear session queue": "セッションキューをクリア",
  "Exit cinema": "シネマ表示を終了",

  // Pairing and connection states
  "Connecting to workspace": "ワークスペースに接続中",
  "Waiting for network.": "ネットワークを待っています。",
  "Validating the pairing link and preparing your session.":
    "ペアリングリンクを検証し、セッションを準備しています。",
  "Pair with this environment": "この環境とペアリング",
  "Pairing with this environment": "この環境とペアリング中",
  "Pairing token": "ペアリングトークン",
  "Paste a one-time token or pairing secret":
    "一度限りのトークンまたはペアリングシークレットを貼り付け",
  "Admin password": "管理者パスワード",
  Password: "パスワード",
  "Enter the admin password": "管理者パスワードを入力",
  Disconnected: "切断済み",
  "Reconnecting…": "再接続中…",
  "Client and server versions differ": "クライアントとサーバーのバージョンが異なります",
  "Dismiss version mismatch warning": "バージョン不一致の警告を閉じる",

  // Updates and releases
  "Update available": "更新があります",
  "Update downloaded": "更新をダウンロードしました",
  "Restart to update": "再起動して更新",
  "Restart the app from the update button to install it.":
    "更新ボタンからアプリを再起動してインストールしてください。",
  "Could not start update download": "更新のダウンロードを開始できませんでした",
  "Could not download update": "更新をダウンロードできませんでした",
  "Could not install update": "更新をインストールできませんでした",
  "Could not open release": "リリースを開けませんでした",
  "Dismiss update": "更新通知を閉じる",
  "View macOS update": "macOS 版の更新を表示",
  "Open the Club Code releases page in your browser to install the DMG.":
    "ブラウザーで Club Code のリリースページを開き、DMG をインストールしてください。",
  "Intel build on Apple Silicon": "Apple Silicon 上の Intel ビルド",
  "Release checklist": "リリースチェックリスト",
  "Reload app": "アプリを再読み込み",

  // Notifications, errors, and utility labels
  "Dismiss error": "エラーを閉じる",
  "Dismiss notification": "通知を閉じる",
  "Dismiss provider status": "プロバイダー状態を閉じる",
  "Dismiss provider update notice": "プロバイダー更新通知を閉じる",
  "Dismiss until next launch": "次回起動まで閉じる",
  "Dismiss until provider status changes": "プロバイダー状態が変わるまで閉じる",
  "Copy error": "エラーをコピー",
  "Copy command": "コマンドをコピー",
  "Unable to run command": "コマンドを実行できません",
  "Repository lookup failed": "リポジトリの検索に失敗しました",
  "Unable to open pull request link": "プルリクエストのリンクを開けません",
  "Some usage windows could not refresh.": "一部の使用状況ウィンドウを更新できませんでした。",
  "Paid usage is stale; showing the last provider-reported values.":
    "有料使用状況が古いため、プロバイダーが最後に報告した値を表示しています。",
  "Current balance": "現在の残高",
  "Current balance is not reported by this provider.":
    "このプロバイダーは現在の残高を報告していません。",
  "Provider usage": "プロバイダー使用状況",
  "Provider usage limits": "プロバイダー使用上限",
  "Refresh provider usage": "プロバイダー使用状況を更新",
  "Working for": "作業時間",
  "Daily generating time for the last few months; brighter cells mean more time.":
    "過去数か月の日別生成時間です。明るいセルほど時間が長いことを示します。",
  "Weather unavailable": "天気情報を利用できません",
  "Loading weather…": "天気を読み込み中…",
  "Open-Meteo.com": "Open-Meteo.com",
  "Loading files…": "ファイルを読み込み中…",
  "Loading work log...": "作業ログを読み込み中...",
  "Actions are project-scoped commands you can run from the top bar or keybindings.":
    "アクションはプロジェクト単位のコマンドで、トップバーまたはキーバインドから実行できます。",
  "Script actions": "スクリプト操作",
  "Subscription actions": "サブスクリプション操作",
  "Upstream checks": "アップストリーム確認",
  "Local checks": "ローカル確認",
  "Add action": "アクションを追加",
  "Delete action": "アクションを削除",
  "Run on": "実行タイミング",
  "Grouping rule": "グループ化ルール",
  "Project grouping": "プロジェクトのグループ化",
  "Project grouping rule": "プロジェクトのグループ化ルール",
  "Choose icon": "アイコンを選択",
  "Press shortcut": "ショートカットを押してください",
  Keybinding: "キーバインド",
  "This action cannot be undone.": "この操作は取り消せません。",
};
