/** Core shell strings that are not owned by the settings catalog. */
export const CORE_JA: Readonly<Record<string, string>> = {
  "Allow Auto Nudge again": "Auto Nudge を再許可",
  "Auto Nudge": "自動ナッジ",
  Back: "戻る",
  Cancel: "キャンセル",
  Collapse: "折りたたむ",
  Continue: "続行",
  Delete: "削除",
  Disabled: "無効",
  Done: "完了",
  Enabled: "有効",
  English: "英語",
  Expand: "展開する",
  Japanese: "日本語",
  Loading: "読み込み中",
  Off: "オフ",
  On: "オン",
  Reset: "リセット",
  Save: "保存",
  Saved: "保存済み",
  Settings: "設定",
  Stop: "停止",
  "System default": "システム既定",
  "Try again": "もう一度試す",
  Unavailable: "利用不可",
};
