/** First-party interface labels only. User content is not a translation source. */
export const SETTINGS_JA: Readonly<Record<string, string>> = {
  Settings: "設定",
  "Restore defaults": "既定値に戻す",
  Back: "戻る",
  Preferences: "環境設定",
  Appearance: "外観",
  Ambiance: "アンビエンス",
  "Chat & Threads": "チャットとスレッド",
  Notifications: "通知",
  Keybindings: "キーバインド",
  "AI & Integrations": "AI と連携",
  Providers: "プロバイダー",
  "Source Control": "ソース管理",
  WebUI: "Web UI",
  Data: "データ",
  Usage: "使用状況",
  Archive: "アーカイブ",
  "Recently Deleted": "最近削除した項目",
  Advanced: "詳細設定",
  System: "システム",
  Diagnostics: "診断",
  About: "このアプリについて",
  Apply: "適用",
  Save: "保存",
  "Saving…": "保存中…",
  Cancel: "キャンセル",
  Add: "追加",
  Remove: "削除",
  Delete: "削除",
  Edit: "編集",
  Rename: "名前を変更",
  Change: "変更",
  Clear: "クリア",
  Reload: "再読み込み",
  Refresh: "更新",
  Reset: "リセット",
  Restore: "復元",
  Done: "完了",
  Next: "次へ",
  Test: "テスト",
  Use: "使用",
  Default: "既定",
  Custom: "カスタム",
  Available: "利用可能",
  Unavailable: "利用不可",
  Checking: "確認中",
  Checked: "確認済み",
  On: "オン",
  Off: "オフ",
  Auto: "自動",
  Always: "常時",
  Local: "ローカル",
  Sensitive: "機密",
  Fixed: "固定",
  Random: "ランダム",
  Medium: "中",
  English: "英語",
  Japanese: "日本語",
  Theme: "テーマ",
  Light: "ライト",
  Dark: "ダーク",
  "Theme preference": "テーマ設定",
  "Branding prefix": "ブランド名の接頭辞",
  "Rename the first word of the sidebar wordmark while keeping the Code suffix.":
    "サイドバーのワードマークで、末尾の「Code」を残したまま先頭の単語を変更します。",
  "Accent color": "アクセントカラー",
  "Choose the primary color used for buttons, focused controls, and rings.":
    "ボタン、フォーカス中のコントロール、リングに使うメインカラーを選びます。",
  "Sidebar color": "サイドバーの色",
  "Choose the color used by the animated sidebar stars and glow.":
    "サイドバーの星のアニメーションと光彩に使う色を選びます。",
  "Sidebar image": "サイドバー画像",
  "Sidebar image file": "サイドバー画像ファイル",
  "Use a local PNG, JPEG, GIF, or WebP image at the bottom of the sidebar.":
    "サイドバー下部にローカルの PNG、JPEG、GIF、WebP 画像を表示します。",
  "Sidebar search": "サイドバー検索",
  "Show sidebar search": "サイドバー検索を表示",
  "Show the search button at the top of the sidebar.": "サイドバー上部に検索ボタンを表示します。",
  "Sidebar mascot": "サイドバーのマスコット",
  "Show sidebar mascot": "サイドバーのマスコットを表示",
  "Show the sidebar image at the bottom of the sidebar.":
    "サイドバー下部にサイドバー画像を表示します。",
  "Sidebar attribution": "サイドバーの帰属表示",
  "Show sidebar attribution": "サイドバーの帰属表示を表示",
  "Show the attribution message below the sidebar image.":
    "サイドバー画像の下に帰属メッセージを表示します。",
  "Background animations": "バックグラウンドアニメーション",
  "Keep animations running in background": "バックグラウンドでもアニメーションを継続",
  "Sidebar star speed": "サイドバーの星の速度",
  "Sidebar star speed multiplier": "サイドバーの星の速度倍率",
  "Adjust how quickly the decorative sidebar stars drift.":
    "サイドバーの装飾用の星が流れる速さを調整します。",
  "Decrease sidebar star speed": "サイドバーの星を遅くする",
  "Increase sidebar star speed": "サイドバーの星を速くする",
  "Time format": "時刻形式",
  "Timestamp format": "タイムスタンプ形式",
  "System default": "システム既定",
  "System default follows your browser or OS clock preference.":
    "システム既定では、ブラウザーまたは OS の時計設定に従います。",
  seconds: "秒",
  "Assistant output": "アシスタント出力",
  "Show token-by-token output while a response is in progress.":
    "応答の生成中にトークン単位で出力を表示します。",
  "Stream assistant messages": "アシスタントメッセージをストリーミング表示",
  "Chat selection copy": "チャット選択範囲のコピー",
  "Chat selection copy format": "チャット選択範囲のコピー形式",
  "Choose what Ctrl-C and right-click Copy put on the clipboard for selected chat message text.":
    "選択したチャットメッセージを Ctrl+C または右クリックでコピーするときの形式を選びます。",
  Markdown: "Markdown",
  "Plain text": "プレーンテキスト",
  "New threads": "新しいスレッド",
  "Default thread mode": "既定のスレッドモード",
  "Pick the default workspace mode for newly created draft threads.":
    "新しく作成する下書きスレッドの既定ワークスペースモードを選びます。",
  "New worktree": "新しいワークツリー",
  "System prompt": "システムプロンプト",
  "Edit the file prepended to the first message in each new thread.":
    "新しい各スレッドの最初のメッセージの前に追加するファイルを編集します。",
  "Archive confirmation": "アーカイブの確認",
  "Confirm thread archiving": "スレッドのアーカイブを確認",
  "Require a second click on the inline archive action before a thread is archived.":
    "スレッドをアーカイブする前に、インラインのアーカイブ操作をもう一度クリックする必要があります。",
  "Delete confirmation": "削除の確認",
  "Confirm thread deletion": "スレッドの削除を確認",
  "Ask before deleting a thread and its chat history.":
    "スレッドとチャット履歴を削除する前に確認します。",
  "Default editor": "既定のエディター",
  "Choose how file links open from chats and activity.":
    "チャットやアクティビティからファイルリンクを開く方法を選びます。",
  "Add project starts in": "プロジェクト追加の開始場所",
  "Add project base directory": "プロジェクト追加の基準ディレクトリ",
  "Keep awake": "スリープを防止",
  "During chats": "チャット中",
  "Version Control": "バージョン管理",
  "Source Control Providers": "ソース管理プロバイダー",
  "Fetch interval": "フェッチ間隔",
  "Automatic Git fetch interval in seconds": "Git の自動フェッチ間隔（秒）",
  "Decrease fetch interval": "フェッチ間隔を短くする",
  "Increase fetch interval": "フェッチ間隔を長くする",
  "Rescan Git and hosting integrations": "Git とホスティング連携を再スキャン",
  Scan: "スキャン",
  "Text generation model": "テキスト生成モデル",
  "Configure the model used for generated commit messages, PR titles, and similar Git text.":
    "コミットメッセージ、PR タイトルなどの Git テキスト生成に使うモデルを設定します。",
  Version: "バージョン",
  "Check for Updates": "更新を確認",
  "Source update checks are only available in the desktop app.":
    "ソース更新の確認はデスクトップアプリでのみ利用できます。",
  "View diagnostics": "診断を表示",
  "Draw an animated weather layer over the app. Off keeps the default sidebar stars.":
    "アプリ全体に天候アニメーションを描画します。オフでは既定のサイドバーの星を維持します。",
  "Enable ambiance": "アンビエンスを有効化",
  Effect: "エフェクト",
  "Pick the weather drawn behind your work. Previews are live.":
    "作業の背後に描画する天候を選びます。プレビューはリアルタイムです。",
  Stars: "星",
  Rain: "雨",
  Snow: "雪",
  Matrix: "Matrix",
  Fire: "炎",
  Intensity: "強度",
  "Ambiance intensity": "アンビエンスの強度",
  "Baseline density before the thread has any say.": "スレッドの状態を反映する前の基準密度です。",
  "React to thread": "スレッドに反応",
  "How much of the run the weather is allowed to hear.":
    "実行状況を天候エフェクトにどの程度反映するかを設定します。",
  Surfaces: "描画面",
  "Where the weather draws. Turning off the thread area keeps message text on a flat background; the composer surface tints the prompt frame with the current conditions.":
    "天候を描画する場所です。スレッド領域をオフにするとメッセージは平坦な背景になり、入力欄では現在の状態に合わせてプロンプト枠が色付きます。",
  "Weather color": "天候の色",
  "Defaults to the accent color set in Appearance.":
    "既定では外観で設定したアクセントカラーを使います。",
  Presentation: "表示形式",
  Floating: "フローティング",
  Layout: "レイアウト",
  "Thread completion notifications": "スレッド完了通知",
  "Enable thread completion notifications": "スレッド完了通知を有効化",
  "Add provider": "プロバイダーを追加",
  "Add provider instance": "プロバイダーインスタンスを追加",
  "Provider instance added": "プロバイダーインスタンスを追加しました",
  "Could not add provider instance": "プロバイダーインスタンスを追加できませんでした",
  Label: "ラベル",
  "Label (optional)": "ラベル（任意）",
  "e.g. Work": "例: 仕事用",
  "Instance ID": "インスタンス ID",
  "Provider instance accent color": "プロバイダーインスタンスのアクセントカラー",
  "Used to distinguish this instance in picker rails and model lists.":
    "選択欄やモデル一覧でこのインスタンスを区別するために使います。",
  Driver: "ドライバー",
  "Instance settings": "インスタンス設定",
  "New chat defaults": "新規チャットの既定値",
  "New chat defaults and configuration for this provider instance.":
    "このプロバイダーインスタンスの新規チャット既定値と構成です。",
  Models: "モデル",
  "Environment variables": "環境変数",
  "Add variables to pass API keys, base URLs, or other per-instance CLI settings.":
    "API キー、ベース URL、その他インスタンス別 CLI 設定を渡す変数を追加します。",
  "Sensitive values are stored separately and are not returned to the app after saving.":
    "機密値は別に保存され、保存後にアプリへ返されません。",
  "Display name": "表示名",
  "Shown in the provider list. Optional.": "プロバイダー一覧に表示します。任意です。",
  "Routing key used by threads and sessions. Letters, digits, '-', or '_'.":
    "スレッドとセッションで使うルーティングキーです。英数字、-、_ を使用できます。",
  "Use default": "既定値を使用",
  "Use for new chats by default": "新規チャットで既定として使用",
  "New chats start on this provider. Click to clear.":
    "新規チャットはこのプロバイダーで開始します。クリックすると解除します。",
  "New chats keep the last model used on this instance.":
    "新規チャットではこのインスタンスで最後に使ったモデルを維持します。",
  "Option defaults become editable once the provider reports this model.":
    "プロバイダーがこのモデルを報告すると、オプションの既定値を編集できます。",
  "This model does not report configurable options.":
    "このモデルは構成可能なオプションを報告しません。",
  "Refresh provider status": "プロバイダー状態を更新",
  "Restart provider runtime": "プロバイダーランタイムを再起動",
  "Restarting…": "再起動中…",
  "Delete instance": "インスタンスを削除",
  "Complete the provider login in the PowerShell window, then refresh status.":
    "PowerShell ウィンドウでプロバイダーへのログインを完了し、状態を更新してください。",
  Authenticated: "認証済み",
  "Not authenticated": "未認証",
  "Not configured": "未構成",
  "Status unknown": "状態不明",
  "Update available": "更新があります",
  "Update available — view details": "更新があります — 詳細を表示",
  "Copy update command": "更新コマンドをコピー",
  "Run it in a terminal when you are ready to update.":
    "更新する準備ができたらターミナルで実行してください。",
  "Manage local backend": "ローカルバックエンドを管理",
  "Local backend access": "ローカルバックエンドへのアクセス",
  "Production server": "本番サーバー",
  "Server environment": "サーバー環境",
  "Rescan server environment": "サーバー環境を再スキャン",
  "Network access": "ネットワークアクセス",
  "Enable network access": "ネットワークアクセスを有効化",
  HTTPS: "HTTPS",
  "Enable HTTPS": "HTTPS を有効化",
  "WebUI uses HTTPS.": "Web UI は HTTPS を使用しています。",
  "Download certificate": "証明書をダウンロード",
  "Admin password": "管理者パスワード",
  "Set the password used for owner login from the pairing screen.":
    "ペアリング画面からオーナーとしてログインする際のパスワードを設定します。",
  "Password sign-in is on.": "パスワードログインはオンです。",
  "Password sign-in is off.": "パスワードログインはオフです。",
  "Enable password authentication": "パスワード認証を有効化",
  "Disable password authentication?": "パスワード認証を無効にしますか？",
  "Password authentication disabled": "パスワード認証を無効にしました",
  "Clear stored password": "保存済みパスワードを消去",
  "Confirm password": "パスワードを確認",
  "Admin password updated": "管理者パスワードを更新しました",
  "Create pairing link": "ペアリングリンクを作成",
  "Create link": "リンクを作成",
  "Pairing link — scan to open on another device":
    "ペアリングリンク — スキャンして別のデバイスで開く",
  "Pairing code": "ペアリングコード",
  "Pairing URL": "ペアリング URL",
  "Pairing method": "ペアリング方法",
  "Host + Code": "ホスト + コード",
  "Copy code": "コードをコピー",
  "Token only": "トークンのみ",
  "Copy selected endpoint": "選択したエンドポイントをコピー",
  "Choose endpoint to copy": "コピーするエンドポイントを選択",
  "Show QR code": "QR コードを表示",
  "Client label (optional)": "クライアントラベル（任意）",
  "e.g. Living room iPad": "例: リビングの iPad",
  "Authorized clients": "認証済みクライアント",
  "This device": "このデバイス",
  Disconnect: "接続解除",
  "No pairing links or client sessions.":
    "ペアリングリンクまたはクライアントセッションはありません。",
  "New browser logins will need a pairing link.":
    "新しいブラウザーログインにはペアリングリンクが必要です。",
  "Other paired clients will need a new pairing link before reconnecting.":
    "他のペアリング済みクライアントは、再接続前に新しいペアリングリンクが必要です。",
  "Pairing links and client-session management are only available to owner sessions for this backend.":
    "ペアリングリンクとクライアントセッション管理は、このバックエンドのオーナーセッションでのみ利用できます。",
  "Reachable at": "接続先",
  "Could not create pairing URL": "ペアリング URL を作成できませんでした",
  "Could not revoke pairing link": "ペアリングリンクを取り消せませんでした",
  "Could not revoke client access": "クライアントアクセスを取り消せませんでした",
  "Could not revoke other clients": "他のクライアントを取り消せませんでした",
  "Could not update admin password": "管理者パスワードを更新できませんでした",
  "Could not disable password authentication": "パスワード認証を無効にできませんでした",
  "Could not update HTTPS": "HTTPS を更新できませんでした",
  "Could not update network access": "ネットワークアクセスを更新できませんでした",
  "Collect usage statistics": "使用統計を収集",
  "Data collection": "データ収集",
  "Token usage by provider and model": "プロバイダー・モデル別のトークン使用量",
  "Tokens by provider and model": "プロバイダー・モデル別トークン",
  "Provider and model attribution will appear after output tokens are recorded.":
    "出力トークンが記録されると、プロバイダーとモデルの内訳が表示されます。",
  "Usage stats are unavailable right now. Reconnect to the server and try again.":
    "現在、使用統計を利用できません。サーバーに再接続してからもう一度お試しください。",
  "Not currently reported by this provider.": "現在このプロバイダーから報告されていません。",
  Keybinding: "キーバインド",
  "Add keybinding": "キーバインドを追加",
  "Cancel new keybinding": "新しいキーバインドをキャンセル",
  "Search keybindings": "キーバインドを検索",
  "No keybindings match your search.": "検索に一致するキーバインドはありません。",
  "Unable to save keybinding": "キーバインドを保存できませんでした",
  "Unable to remove keybinding": "キーバインドを削除できませんでした",
  "Unable to open keybindings file": "キーバインドファイルを開けませんでした",
  "Unable to copy keybindings path": "キーバインドのパスをコピーできませんでした",
  "Saved environments": "保存済み環境",
  "Add saved environment": "保存済み環境を追加",
  "Add environment": "環境を追加",
  "Remove saved environment": "保存済み環境を削除",
  "Remove saved environment?": "保存済み環境を削除しますか？",
  "No remote servers paired": "ペアリング済みリモートサーバーはありません",
  "Archived threads": "アーカイブ済みスレッド",
  "Loading archived threads": "アーカイブ済みスレッドを読み込み中",
  "Could not load archived threads": "アーカイブ済みスレッドを読み込めませんでした",
  "No archived threads": "アーカイブ済みスレッドはありません",
  "Checking connected environments.": "接続済み環境を確認しています。",
  "Archived threads will appear here.": "アーカイブ済みスレッドはここに表示されます。",
  Unarchive: "アーカイブを解除",
  "Failed to unarchive thread": "スレッドのアーカイブを解除できませんでした",
  "Move to Recycle Bin": "ごみ箱へ移動",
  "Empty Recycle Bin": "ごみ箱を空にする",
  "Loading recently deleted threads": "最近削除したスレッドを読み込み中",
  "Could not load recently deleted threads": "最近削除したスレッドを読み込めませんでした",
  "No recently deleted threads": "最近削除したスレッドはありません",
  "Threads moved to the Recycle Bin will appear here.":
    "ごみ箱へ移動したスレッドはここに表示されます。",
  "Delete Forever": "完全に削除",
  "Recycle Bin emptied": "ごみ箱を空にしました",
  "Failed to empty Recycle Bin": "ごみ箱を空にできませんでした",
  "Failed to restore thread": "スレッドを復元できませんでした",
  "Failed to delete thread": "スレッドを削除できませんでした",
  "Runtime Overview": "ランタイム概要",
  "Orchestrator Subprocesses": "オーケストレーターのサブプロセス",
  "Orchestrator Health": "オーケストレーターの健全性",
  "Provider Daemon": "プロバイダーデーモン",
  "Provider Pipeline": "プロバイダーパイプライン",
  "Provider Supervisor": "プロバイダースーパーバイザー",
  "Live Processes": "実行中のプロセス",
  "Resource History": "リソース履歴",
  "Trace Diagnostics": "トレース診断",
  "Latest Failures": "最新の失敗",
  "Most Common Failures": "最も多い失敗",
  "Slowest Spans": "最も遅いスパン",
  "Span Logs": "スパンログ",
  "Top Span Names": "上位のスパン名",
  Process: "プロセス",
  Name: "名前",
  Role: "役割",
  Status: "状態",
  Owner: "所有者",
  Command: "コマンド",
  Type: "種類",
  Memory: "メモリ",
  Current: "現在",
  Average: "平均",
  Peak: "ピーク",
  "CPU Time": "CPU 時間",
  "Max Mem": "最大メモリ",
  Kill: "終了",
  Time: "時刻",
  Level: "レベル",
  Span: "スパン",
  Message: "メッセージ",
  Trace: "トレース",
  Activity: "アクティビティ",
  "Send SIGINT": "SIGINT を送信",
  "Send SIGKILL": "SIGKILL を送信",
  "Copy trace ID": "トレース ID をコピー",
  "Copied trace ID": "トレース ID をコピーしました",
  "Open logs folder": "ログフォルダーを開く",
  "Copy logs folder path": "ログフォルダーのパスをコピー",
  "Logs path copied": "ログのパスをコピーしました",
  "Path copied": "パスをコピーしました",
  "Process already exited": "プロセスはすでに終了しています",
  "No projector cursors found.": "プロジェクターカーソルは見つかりませんでした。",
  "No recent daemon commands.": "最近のデーモンコマンドはありません。",
  "No recent daemon runtime events.": "最近のデーモンランタイムイベントはありません。",
  "No recent orchestration events.": "最近のオーケストレーションイベントはありません。",
  "No supervisor session counts found.": "スーパーバイザーのセッション数は見つかりませんでした。",
};
