/**
 * Exact English-to-Japanese translations for the settings UI.
 *
 * Keys intentionally mirror authored UI text. This lets the legacy-text bridge
 * localize existing settings surfaces without guessing or translating operator
 * content, paths, provider output, or other dynamic values.
 */
export const SETTINGS_JA: Readonly<Record<string, string>> = {
  // Settings shell and navigation
  Settings: "設定",
  "Restore defaults": "既定値に戻す",
  Back: "戻る",
  Preferences: "環境設定",
  Appearance: "外観",
  Ambiance: "アンビエンス",
  "Chat & Threads": "チャットとスレッド",
  Notifications: "通知",
  "Files & Diffs": "ファイルと差分",
  Keybindings: "キーバインド",
  "AI & Integrations": "AI と連携",
  Providers: "プロバイダー",
  "Source Control": "ソース管理",
  WebUI: "Web UI",
  Data: "データ",
  Usage: "使用状況",
  Archive: "アーカイブ",
  "Recently Deleted": "最近削除した項目",
  Advanced: "詳細設定",
  System: "システム",
  Diagnostics: "診断",
  About: "このアプリについて",
  Apply: "適用",
  Save: "保存",
  "Saving…": "保存中…",
  Cancel: "キャンセル",
  Add: "追加",
  Remove: "削除",
  Delete: "削除",
  Edit: "編集",
  Rename: "名前を変更",
  Change: "変更",
  Clear: "クリア",
  Reload: "再読み込み",
  Refresh: "更新",
  Reset: "リセット",
  Restore: "復元",
  Done: "完了",
  Next: "次へ",
  Test: "テスト",
  Use: "使用",
  Default: "既定",
  Custom: "カスタム",
  Available: "利用可能",
  Unavailable: "利用不可",
  Checking: "確認中",
  Checked: "確認済み",
  On: "オン",
  Off: "オフ",
  Auto: "自動",
  Always: "常時",
  Local: "ローカル",
  Sensitive: "機密",
  Fixed: "固定",
  Random: "ランダム",
  Small: "小",
  Medium: "中",
  Large: "大",
  English: "英語",
  Japanese: "日本語",
  "English + Japanese": "英語 + 日本語",

  // General appearance
  Theme: "テーマ",
  Light: "ライト",
  Dark: "ダーク",
  "Theme preference": "テーマ設定",
  "Choose how Club Code looks across the app.": "Club Code 全体の外観を選びます。",
  "Branding prefix": "ブランド名の接頭辞",
  "Rename the first word of the sidebar wordmark while keeping the Code suffix.":
    "サイドバーのワードマークで、末尾の「Code」を残したまま先頭の単語を変更します。",
  "Accent color": "アクセントカラー",
  "Choose the primary color used for buttons, focused controls, and rings.":
    "ボタン、フォーカス中のコントロール、リングに使うメインカラーを選びます。",
  "Sidebar color": "サイドバーの色",
  "Choose the color used by the animated sidebar stars and glow.":
    "サイドバーの星のアニメーションと光彩に使う色を選びます。",
  "Sidebar image": "サイドバー画像",
  "Sidebar image file": "サイドバー画像ファイル",
  "Use a local PNG, JPEG, GIF, or WebP image at the bottom of the sidebar.":
    "サイドバー下部にローカルの PNG、JPEG、GIF、WebP 画像を表示します。",
  "Sidebar search": "サイドバー検索",
  "Show sidebar search": "サイドバー検索を表示",
  "Show the search button at the top of the sidebar.": "サイドバー上部に検索ボタンを表示します。",
  "Sidebar mascot": "サイドバーのマスコット",
  "Show sidebar mascot": "サイドバーのマスコットを表示",
  "Show the sidebar image at the bottom of the sidebar.":
    "サイドバー下部にサイドバー画像を表示します。",
  "Sidebar attribution": "サイドバーの帰属表示",
  "Show sidebar attribution": "サイドバーの帰属表示を表示",
  "Show the attribution message below the sidebar image.":
    "サイドバー画像の下に帰属メッセージを表示します。",
  "Background animations": "バックグラウンドアニメーション",
  "Keep animations running in background": "バックグラウンドでもアニメーションを継続",
  "Keep decorative animations running when Club Code is hidden or unfocused.":
    "Club Code が非表示またはフォーカス外でも装飾アニメーションを続けます。",
  "Sidebar star speed": "サイドバーの星の速度",
  "Sidebar star speed multiplier": "サイドバーの星の速度倍率",
  "Adjust how quickly the decorative sidebar stars drift.":
    "サイドバーの装飾用の星が流れる速さを調整します。",
  "Decrease sidebar star speed": "サイドバーの星を遅くする",
  "Increase sidebar star speed": "サイドバーの星を速くする",
  "Time format": "時刻形式",
  "Timestamp format": "タイムスタンプ形式",
  "System default": "システム既定",
  "System default follows your browser or OS clock preference.":
    "システム既定では、ブラウザーまたは OS の時計設定に従います。",
  "Desktop window opacity": "デスクトップウィンドウの不透明度",
  "Window opacity": "ウィンドウの不透明度",
  "Window transparency and safety": "ウィンドウの透明度と安全性",
  "Transparent desktop window": "デスクトップウィンドウを透明化",
  "Make the entire native Club Code window translucent. Lower values can reduce text legibility.":
    "Club Code のネイティブウィンドウ全体を半透明にします。値を下げると文字が読みにくくなる場合があります。",
  "Lower is more transparent; 5% is faint and 100% is solid.":
    "値が低いほど透明になります。5% は非常に薄く、100% は不透明です。",
  "Restore opaque window": "不透明なウィンドウに戻す",
  "Could not change window opacity": "ウィンドウの不透明度を変更できませんでした",
  "Could not read window opacity": "ウィンドウの不透明度を読み取れませんでした",

  // Workflow and chat
  "Agent workflow observatory": "エージェントワークフロー観測",
  "Show agent workflow observatory": "エージェントワークフロー観測を表示",
  "Show the Plan panel's Workflow tab with provider-reported agent hierarchy and activity. Turning this off hides the tab; it never stops agent work.":
    "Plan パネルの Workflow タブに、プロバイダーが報告したエージェント階層と活動を表示します。オフにするとタブだけが非表示になり、エージェントの作業は停止しません。",
  "Workflow silence warning": "ワークフロー無通信警告",
  "Workflow silence warning seconds": "ワークフロー無通信警告（秒）",
  "Warn when a running or waiting agent has no provider-reported activity for this long. It is a 'possibly stalled' warning, never proof that work stopped.":
    "実行中または待機中のエージェントについて、指定時間プロバイダーから活動報告がない場合に警告します。これは「停止している可能性」の警告であり、作業停止の証明ではありません。",
  "Decrease workflow silence warning": "無通信警告時間を短くする",
  "Increase workflow silence warning": "無通信警告時間を長くする",
  seconds: "秒",
  "Assistant output": "アシスタント出力",
  "Show token-by-token output while a response is in progress.":
    "応答の生成中にトークン単位で出力を表示します。",
  "Stream assistant messages": "アシスタントメッセージをストリーミング表示",
  "Auto-open task panel": "タスクパネルを自動で開く",
  "Open the task panel automatically": "タスクパネルを自動的に開く",
  "Open the right-side plan and task panel the first time steps appear, until a thread is manually opened or closed.":
    "スレッドを手動で開閉するまで、手順が初めて現れたときに右側の計画・タスクパネルを開きます。",
  "Chat selection copy": "チャット選択範囲のコピー",
  "Chat selection copy format": "チャット選択範囲のコピー形式",
  "Choose what Ctrl-C and right-click Copy put on the clipboard for selected chat message text.":
    "選択したチャットメッセージを Ctrl+C または右クリックでコピーするときの形式を選びます。",
  Markdown: "Markdown",
  "Plain text": "プレーンテキスト",
  "New threads": "新しいスレッド",
  "Default thread mode": "既定のスレッドモード",
  "Pick the default workspace mode for newly created draft threads.":
    "新しく作成する下書きスレッドの既定ワークスペースモードを選びます。",
  "New worktree": "新しいワークツリー",
  "System prompt": "システムプロンプト",
  "Edit the file prepended to the first message in each new thread.":
    "新しい各スレッドの最初のメッセージの前に追加するファイルを編集します。",
  "Archive confirmation": "アーカイブの確認",
  "Confirm thread archiving": "スレッドのアーカイブを確認",
  "Require a second click on the inline archive action before a thread is archived.":
    "スレッドをアーカイブする前に、インラインのアーカイブ操作をもう一度クリックする必要があります。",
  "Delete confirmation": "削除の確認",
  "Confirm thread deletion": "スレッドの削除を確認",
  "Ask before deleting a thread and its chat history.":
    "スレッドとチャット履歴を削除する前に確認します。",

  // Files, source control, and system
  "Default editor": "既定のエディター",
  "Choose how file links open from chats and activity.":
    "チャットやアクティビティからファイルリンクを開く方法を選びます。",
  "Diff line wrapping": "差分の行折り返し",
  "Wrap diff lines by default": "差分行を既定で折り返す",
  "Set the default wrap state when the diff panel opens.":
    "差分パネルを開いたときの既定の折り返し状態を設定します。",
  "Hide whitespace changes": "空白のみの変更を非表示",
  "Hide whitespace changes by default": "空白のみの変更を既定で非表示",
  "Set whether the diff panel ignores whitespace-only edits by default.":
    "差分パネルで空白のみの編集を既定で無視するか設定します。",
  "Add project starts in": "プロジェクト追加の開始場所",
  "Add project base directory": "プロジェクト追加の基準ディレクトリ",
  "Keep awake": "スリープを防止",
  "Prevent your computer and screen from sleeping while Club Code is working.":
    "Club Code の作業中にコンピューターと画面がスリープしないようにします。",
  "During chats": "チャット中",
  "Version Control": "バージョン管理",
  "Source Control Providers": "ソース管理プロバイダー",
  "Fetch interval": "フェッチ間隔",
  "Automatic Git fetch interval in seconds": "Git の自動フェッチ間隔（秒）",
  "Decrease fetch interval": "フェッチ間隔を短くする",
  "Increase fetch interval": "フェッチ間隔を長くする",
  "Rescan Git and hosting integrations": "Git とホスティング連携を再スキャン",
  Scan: "スキャン",
  "Text generation model": "テキスト生成モデル",
  "Configure the model used for generated commit messages, PR titles, and similar Git text.":
    "コミットメッセージ、PR タイトルなどの Git テキスト生成に使うモデルを設定します。",
  Version: "バージョン",
  "Check for Updates": "更新を確認",
  "Source update checks are only available in the desktop app.":
    "ソース更新の確認はデスクトップアプリでのみ利用できます。",
  "View diagnostics": "診断を表示",

  // Ambiance and Matrix
  "Draw an animated weather layer over the app. Off keeps the default sidebar stars.":
    "アプリ全体に天候アニメーションを描画します。オフでは既定のサイドバーの星を維持します。",
  "Enable ambiance": "アンビエンスを有効化",
  Effect: "エフェクト",
  "Pick the weather drawn behind your work. Previews are live.":
    "作業の背後に描画する天候を選びます。プレビューはリアルタイムです。",
  Stars: "星",
  Rain: "雨",
  Snow: "雪",
  Matrix: "Matrix",
  Fire: "炎",
  Intensity: "強度",
  "Ambiance intensity": "アンビエンスの強度",
  "Baseline density before the thread has any say.": "スレッドの状態を反映する前の基準密度です。",
  "React to thread": "スレッドに反応",
  "How much of the run the weather is allowed to hear.":
    "実行状況を天候エフェクトにどの程度反映するかを設定します。",
  Surfaces: "描画面",
  "Where the weather draws. Turning off the thread area keeps message text on a flat background; the composer surface tints the prompt frame with the current conditions.":
    "天候を描画する場所です。スレッド領域をオフにするとメッセージは平坦な背景になり、入力欄では現在の状態に合わせてプロンプト枠が色付きます。",
  "Weather color": "天候の色",
  "Defaults to the accent color set in Appearance.":
    "既定では外観で設定したアクセントカラーを使います。",
  "Falling effects": "落下エフェクト",
  "Show falling effects": "落下エフェクトを表示",
  "Let snow, rain, or Matrix characters drift across the whole Club Code window.":
    "Club Code ウィンドウ全体に雪、雨、Matrix 文字を流します。",
  "Falling effect": "落下エフェクト",
  "Choose what falls through the window.": "ウィンドウ内を落下するものを選びます。",
  "Effect density": "エフェクト密度",
  "Falling effect density multiplier": "落下エフェクトの密度倍率",
  "Decrease falling effect density": "落下エフェクトの密度を下げる",
  "Increase falling effect density": "落下エフェクトの密度を上げる",
  "Effect opacity": "エフェクトの不透明度",
  "Falling effect opacity percent": "落下エフェクトの不透明度（%）",
  "Decrease falling effect opacity": "落下エフェクトを薄くする",
  "Increase falling effect opacity": "落下エフェクトを濃くする",
  "Effect speed": "エフェクト速度",
  "Falling effect speed multiplier": "落下エフェクトの速度倍率",
  "Adjust how quickly the selected effect falls.": "選択したエフェクトが落下する速さを調整します。",
  "Decrease falling effect speed": "落下エフェクトを遅くする",
  "Increase falling effect speed": "落下エフェクトを速くする",
  "Matrix base font size": "Matrix の基準フォントサイズ",
  "Sets the baseline Matrix glyph size for Flat, Forward, Reverse, and Warp. Rain and snow geometry are unchanged. Walk modes continue to use their absolute Start and End sizes.":
    "Flat、Forward、Reverse、Warp の Matrix グリフ基準サイズを設定します。雨と雪の形状は変わりません。Walk モードでは引き続き絶対値の開始・終了サイズを使います。",
  "Walk perspective sizes": "歩行視点のサイズ",
  "Walk symbol lifecycle distance": "歩行モードのシンボル寿命距離",
  "Set how far each randomly placed Matrix stream falls before its font expansion cycle fades out and respawns elsewhere in the background.":
    "ランダムに配置された各 Matrix ストリームが、フォント拡大サイクル後にフェードアウトして背景の別位置に再出現するまでの落下距離を設定します。",
  "Motion from center wind intensity": "中心から外向きの風の強度",
  "Japanese stream ratio percent": "日本語ストリーム比率（%）",
  "At 0%, streams use Roman glyphs and English live terms. At 100%, they use Japanese glyphs and Japanese live terms.":
    "0% ではローマ字グリフと英語のライブ用語、100% では日本語グリフと日本語のライブ用語を使います。",
  "Decrease Japanese stream ratio": "日本語ストリーム比率を下げる",
  "Increase Japanese stream ratio": "日本語ストリーム比率を上げる",
  "Use 2ch-inspired Matrix enrichment": "2ch 風 Matrix 表現を使う",
  "Add tasteful half-width kana, net-culture symbols, and rare intact cat AA tokens to Japanese streams. At 0% Japanese, this option has no visible effect.":
    "日本語ストリームに控えめな半角カナ、ネット文化の記号、まれに崩さない猫 AA トークンを加えます。日本語比率が 0% の場合は表示に影響しません。",
  "Live work vocabulary": "作業中のライブ用語",
  "Use live work vocabulary in Matrix rain": "Matrix 雨で作業中のライブ用語を使う",
  "Matrix color mode": "Matrix のカラーモード",
  "Fixed color": "固定色",
  "Matrix color-cycle speed": "Matrix の色循環速度",
  "Matrix color-cycle speed multiplier": "Matrix の色循環速度倍率",
  "Decrease Matrix color-cycle speed": "Matrix の色循環を遅くする",
  "Increase Matrix color-cycle speed": "Matrix の色循環を速くする",
  "Provider activity links": "プロバイダー活動リンク",
  "Show provider activity links in Matrix rain": "Matrix 雨にプロバイダー活動リンクを表示",
  "Activity inputs": "活動入力",
  "Matrix activity link inputs": "Matrix 活動リンクの入力",
  "Choose which safe provider-observed activity categories may create Matrix pulses and connecting lines. Clear every checkbox to show no activity overlay.":
    "プロバイダーが安全に観測した活動カテゴリのうち、Matrix のパルスと接続線を生成できるものを選びます。すべて外すと活動オーバーレイを表示しません。",
  "Activity link colors": "活動リンクの色",
  "Matrix activity link color mode": "Matrix 活動リンクのカラーモード",
  "Random gives each real link an independent deterministic hue. Matrix follows the selected uniform or per-stream Matrix color animation.":
    "ランダムでは実際の各リンクに独立した決定的な色相を割り当てます。Matrix では選択中の均一またはストリーム別の色アニメーションに従います。",
  "Shimmer colors follow the live Matrix palette when it is available.":
    "利用可能な場合、きらめきの色はライブ Matrix パレットに従います。",

  // Ambient image, video, media, clock, and atmosphere console
  "Ambient image": "アンビエント画像",
  "Show ambient image": "アンビエント画像を表示",
  "An optional GIF or image floats inside the chat area.":
    "任意の GIF または画像をチャット領域内に浮かべます。",
  "Image source": "画像ソース",
  "Ambient image file": "アンビエント画像ファイル",
  "Ambient image folder": "アンビエント画像フォルダー",
  "Image folder cycling": "画像フォルダーの循環",
  "Cycle ambient images": "アンビエント画像を順番に表示",
  "Ambient image cycle seconds": "アンビエント画像の切替秒数",
  Presentation: "表示形式",
  Floating: "フローティング",
  Theater: "シアター",
  Layout: "レイアウト",
  Preset: "プリセット",
  "Preset placement": "プリセットの配置",
  "Choose the starting bottom corner for the preset image.":
    "プリセット画像を最初に置く下側の角を選びます。",
  "Bottom left": "左下",
  "Bottom right": "右下",
  "Preset size": "プリセットサイズ",
  "Preset sizes preserve the image aspect ratio.": "プリセットサイズでは画像の縦横比を維持します。",
  "Ambient glow": "アンビエントの光彩",
  "A soft edge glow uses your selected color.": "選択した色で縁に柔らかな光彩を加えます。",
  "Ambient image glow": "アンビエント画像の光彩",
  "Ambient image glow color": "アンビエント画像の光彩色",
  "Ambient image glow intensity": "アンビエント画像の光彩強度",
  "Reset ambient image": "アンビエント画像をリセット",
  "Restores the layout and glow defaults without deleting the uploaded image.":
    "アップロードした画像を削除せず、レイアウトと光彩を既定値に戻します。",
  "Ambient streaming": "アンビエントストリーミング",
  "Show ambient streaming player": "アンビエントストリーミングプレイヤーを表示",
  "Show streaming player": "ストリーミングプレイヤーを表示",
  "YouTube or Spotify source": "YouTube または Spotify ソース",
  "YouTube or Spotify URL": "YouTube または Spotify の URL",
  "YouTube or Spotify media source": "YouTube または Spotify のメディアソース",
  "Paste a supported YouTube or Spotify URL. Club Code stores only the validated provider, entity type, and ID—not pasted query data.":
    "対応する YouTube または Spotify の URL を貼り付けます。Club Code が保存するのは検証済みのプロバイダー、エンティティ種別、ID のみで、貼り付けたクエリデータは保存しません。",
  "Session URL queue": "セッション URL キュー",
  "Direct queue": "直接キュー",
  "Clear queue": "キューをクリア",
  "Choose YouTube URL queue text file": "YouTube URL キューのテキストファイルを選択",
  "Choose .txt": ".txt を選択",
  "Open playlists": "プレイリストを開く",
  "Your YouTube playlists": "あなたの YouTube プレイリスト",
  "Owned playlist": "所有プレイリスト",
  "Owned YouTube playlist": "所有する YouTube プレイリスト",
  "Search YouTube": "YouTube を検索",
  "Search videos and public playlists": "動画と公開プレイリストを検索",
  "Search public videos and playlists without connecting an account. Club Code sends the query only to its configured YouTube Data API service.":
    "アカウントを接続せずに公開動画とプレイリストを検索します。Club Code は設定済みの YouTube Data API サービスにのみ検索語を送信します。",
  "Open this search on YouTube": "この検索を YouTube で開く",
  "Open selected in YouTube": "選択項目を YouTube で開く",
  "Reset streaming player": "ストリーミングプレイヤーをリセット",
  "Turn the player off and restore its source, presentation, layout, and glow defaults.":
    "プレイヤーをオフにし、ソース、表示形式、レイアウト、光彩を既定値に戻します。",
  "Floating layout": "フローティングレイアウト",
  "Floating corner": "フローティングの配置角",
  "Floating size": "フローティングサイズ",
  "Player glow": "プレイヤーの光彩",
  "Adaptive video edges": "動画の縁に適応",
  "Extend a soft color wash beyond the player, like bias lighting behind a TV.":
    "テレビ背面のバイアス照明のように、プレイヤーの外側へ柔らかな色の光を広げます。",
  "Match video": "動画に合わせる",
  "Uses the current YouTube video artwork. Other players safely use the fixed color.":
    "現在の YouTube 動画アートワークを使います。他のプレイヤーでは安全に固定色を使います。",
  "Video background": "動画背景",
  "Video veil": "動画ベール",
  "Show over cinema video": "シネマ動画の上に表示",
  "Overlay cinema video with falling atmosphere": "シネマ動画に落下アンビエンスを重ねる",
  "Local Media": "ローカルメディア",
  "Choose local media": "ローカルメディアを選択",
  "Choose local audio or video": "ローカルの音声または動画を選択",
  "Local media presentation": "ローカルメディアの表示形式",
  "Local media layout": "ローカルメディアのレイアウト",
  "Local media corner": "ローカルメディアの配置角",
  "Local media size": "ローカルメディアのサイズ",
  "Local media background opacity": "ローカルメディア背景の不透明度",
  "Audio visualizer": "オーディオビジュアライザー",
  "Enable local media audio visualizer": "ローカルメディアのオーディオビジュアライザーを有効化",
  "Audio-reactive visualizer": "音声連動ビジュアライザー",
  "Local media visualizer style": "ローカルメディアのビジュアライザースタイル",
  "Spectrum · classic bars": "スペクトラム · クラシックバー",
  "MilkDrop · bundled presets": "MilkDrop · 同梱プリセット",
  "MilkDrop preset": "MilkDrop プリセット",
  "Search or browse preset": "プリセットを検索または参照",
  "Surprise me": "おまかせ",
  "Previous preset": "前のプリセット",
  "Next preset": "次のプリセット",
  "Auto-cycle MilkDrop presets": "MilkDrop プリセットを自動切替",
  "MilkDrop auto-cycle interval": "MilkDrop 自動切替間隔",
  "Preset blend": "プリセットのブレンド",
  "MilkDrop preset blend duration": "MilkDrop プリセットのブレンド時間",
  "World clock & weather": "世界時計と天気",
  "World clock widget": "世界時計ウィジェット",
  "Show world clock widget": "世界時計ウィジェットを表示",
  "Show a transparent multi-city clock over Club Code. Drag, resize, or collapse it on desktop and LAN browsers.":
    "Club Code 上に透明な複数都市時計を表示します。デスクトップおよび LAN ブラウザーではドラッグ、サイズ変更、折りたたみができます。",
  "Clock style": "時計のスタイル",
  "World clock style": "世界時計のスタイル",
  "World clock cities": "世界時計の都市",
  Cities: "都市",
  "Current weather": "現在の天気",
  "Show current weather in world clock": "世界時計に現在の天気を表示",
  "Open-Meteo terms": "Open-Meteo 利用規約",
  "Window atmosphere": "ウィンドウアンビエンス",
  "Atmosphere console": "アンビエンスコンソール",
  "Show Atmosphere console": "アンビエンスコンソールを表示",
  "Show the movable, resizable local atmosphere command panel. Turning this off fully unmounts the console and stops its listeners and local requests.":
    "移動・サイズ変更可能なローカルアンビエンス操作パネルを表示します。オフにするとコンソールを完全にアンマウントし、リスナーとローカル要求を停止します。",
  "Atmosphere motion": "アンビエンスの動き",
  "Disable all ambient features": "すべてのアンビエント機能を無効化",

  // Notifications and completion alerts
  "Thread completion notifications": "スレッド完了通知",
  "Enable thread completion notifications": "スレッド完了通知を有効化",
  "Alert sound": "通知音",
  "Enable completion alert sound": "完了通知音を有効化",
  "Completion audio": "完了音声",
  "Play a soft original two-tone ping, or cycle through the local files below, only after an observed running turn completes.":
    "実行中だったターンの完了を観測した場合にのみ、穏やかなオリジナルの2音チャイム、または下記ローカルファイルを順番に再生します。",
  "Custom completion alert files": "カスタム完了通知ファイル",
  "Choose custom completion alert files": "カスタム完了通知ファイルを選択",
  "Custom local alert sounds": "カスタムのローカル通知音",
  "No custom files. The built-in ping is used.":
    "カスタムファイルはありません。同梱のチャイムを使います。",
  "Spoken alert": "音声通知",
  "Enable spoken completion alert": "完了時の音声通知を有効化",
  "Speech language": "音声言語",
  "Completion speech language": "完了音声の言語",
  "Choose English, Japanese, or dual-language completion speech.":
    "完了音声を英語、日本語、または2言語から選びます。",
  "English voice preference": "英語音声の設定",
  "English completion voice preference": "英語完了音声の設定",
  "Japanese voice preference": "日本語音声の設定",
  "Japanese completion voice preference": "日本語完了音声の設定",
  "Configured separately from the English voice preference.": "英語音声の設定とは別に構成します。",
  Female: "女性",
  Male: "男性",
  "Dual stereo order": "2言語ステレオの左右順",
  "Dual completion speech stereo order": "2言語完了音声の左右順",
  "English left · Japanese right": "英語を左 · 日本語を右",
  "Japanese left · English right": "日本語を左 · 英語を右",
  "Windows native speech attempts true simultaneous stereo. Browser Web Speech remains centered and sequential.":
    "Windows ネイティブ音声では真の同時ステレオ再生を試みます。ブラウザーの Web Speech は中央から順番に再生されます。",
  "Refresh Windows voices": "Windows 音声を更新",
  "Open Microsoft voice guide": "Microsoft 音声ガイドを開く",
  "Test enabled completion alerts": "有効な完了通知をテスト",

  // Providers and instances
  "Add provider": "プロバイダーを追加",
  "Add provider instance": "プロバイダーインスタンスを追加",
  "Add Codex, Claude, OpenCode, or LM Studio": "Codex、Claude、OpenCode、LM Studio を追加",
  "Provider instance added": "プロバイダーインスタンスを追加しました",
  "Could not add provider instance": "プロバイダーインスタンスを追加できませんでした",
  Label: "ラベル",
  "Label (optional)": "ラベル（任意）",
  "e.g. Work": "例: 仕事用",
  "Instance ID": "インスタンス ID",
  "Provider instance accent color": "プロバイダーインスタンスのアクセントカラー",
  "Used to distinguish this instance in picker rails and model lists.":
    "選択欄やモデル一覧でこのインスタンスを区別するために使います。",
  Driver: "ドライバー",
  "Instance settings": "インスタンス設定",
  "New chat defaults": "新規チャットの既定値",
  "New chat defaults and configuration for this provider instance.":
    "このプロバイダーインスタンスの新規チャット既定値と構成です。",
  Models: "モデル",
  "Environment variables": "環境変数",
  "Add variables to pass API keys, base URLs, or other per-instance CLI settings.":
    "API キー、ベース URL、その他インスタンス別 CLI 設定を渡す変数を追加します。",
  "Sensitive values are stored separately and are not returned to the app after saving.":
    "機密値は別に保存され、保存後にアプリへ返されません。",
  "Display name": "表示名",
  "Shown in the provider list. Optional.": "プロバイダー一覧に表示します。任意です。",
  "Routing key used by threads and sessions. Letters, digits, '-', or '_'.":
    "スレッドとセッションで使うルーティングキーです。英数字、-、_ を使用できます。",
  "Use accent": "アクセントを使用",
  "Use default": "既定値を使用",
  "Use for new chats by default": "新規チャットで既定として使用",
  "New chats start on this provider. Click to clear.":
    "新規チャットはこのプロバイダーで開始します。クリックすると解除します。",
  "New chats keep the last model used on this instance.":
    "新規チャットではこのインスタンスで最後に使ったモデルを維持します。",
  "Option defaults become editable once the provider reports this model.":
    "プロバイダーがこのモデルを報告すると、オプションの既定値を編集できます。",
  "This model does not report configurable options.":
    "このモデルは構成可能なオプションを報告しません。",
  "Refresh provider status": "プロバイダー状態を更新",
  "Restart provider runtime": "プロバイダーランタイムを再起動",
  "Restarting…": "再起動中…",
  "Delete instance": "インスタンスを削除",
  "Set up": "セットアップ",
  "Set up LM Studio Local": "LM Studio Local をセットアップ",
  "LM Studio server URL": "LM Studio サーバー URL",
  "LM Studio Local through Codex OSS": "Codex OSS 経由の LM Studio Local",
  "Complete the provider login in the PowerShell window, then refresh status.":
    "PowerShell ウィンドウでプロバイダーへのログインを完了し、状態を更新してください。",
  Authenticated: "認証済み",
  "Not authenticated": "未認証",
  "Not configured": "未構成",
  "Status unknown": "状態不明",
  "Update available": "更新があります",
  "Update active": "更新中",
  "Update available — view details": "更新があります — 詳細を表示",
  "Copy update command": "更新コマンドをコピー",
  "Run it in a terminal when you are ready to update.":
    "更新する準備ができたらターミナルで実行してください。",

  // WebUI, pairing, and authentication
  "Manage local backend": "ローカルバックエンドを管理",
  "Local backend access": "ローカルバックエンドへのアクセス",
  "Remote Club Code server": "リモート Club Code サーバー",
  "Production server": "本番サーバー",
  "Server environment": "サーバー環境",
  "Rescan server environment": "サーバー環境を再スキャン",
  "Network access": "ネットワークアクセス",
  "Enable network access": "ネットワークアクセスを有効化",
  "Club Code will restart to update the backend listener.":
    "バックエンドのリスナーを更新するため Club Code が再起動します。",
  HTTPS: "HTTPS",
  "Enable HTTPS": "HTTPS を有効化",
  "WebUI uses HTTPS.": "Web UI は HTTPS を使用しています。",
  "Download certificate": "証明書をダウンロード",
  "Admin password": "管理者パスワード",
  "Set the password used for owner login from the pairing screen.":
    "ペアリング画面からオーナーとしてログインする際のパスワードを設定します。",
  "Password sign-in is on.": "パスワードログインはオンです。",
  "Password sign-in is off.": "パスワードログインはオフです。",
  "Enable password authentication": "パスワード認証を有効化",
  "Disable password authentication?": "パスワード認証を無効にしますか？",
  "Password authentication disabled": "パスワード認証を無効にしました",
  "Clear stored password": "保存済みパスワードを消去",
  "Confirm password": "パスワードを確認",
  "Admin password updated": "管理者パスワードを更新しました",
  "Create pairing link": "ペアリングリンクを作成",
  "Create link": "リンクを作成",
  "Pairing link — scan to open on another device":
    "ペアリングリンク — スキャンして別のデバイスで開く",
  "Pairing code": "ペアリングコード",
  "Pairing URL": "ペアリング URL",
  "Pairing method": "ペアリング方法",
  "Host + Code": "ホスト + コード",
  "Copy code": "コードをコピー",
  "Token only": "トークンのみ",
  "Copy selected endpoint": "選択したエンドポイントをコピー",
  "Choose endpoint to copy": "コピーするエンドポイントを選択",
  "Show QR code": "QR コードを表示",
  "Client label (optional)": "クライアントラベル（任意）",
  "e.g. Living room iPad": "例: リビングの iPad",
  "Authorized clients": "認証済みクライアント",
  "This device": "このデバイス",
  Disconnect: "接続解除",
  "No pairing links or client sessions.":
    "ペアリングリンクまたはクライアントセッションはありません。",
  "New browser logins will need a pairing link.":
    "新しいブラウザーログインにはペアリングリンクが必要です。",
  "Other paired clients will need a new pairing link before reconnecting.":
    "他のペアリング済みクライアントは、再接続前に新しいペアリングリンクが必要です。",
  "Pairing links and client-session management are only available to owner sessions for this backend.":
    "ペアリングリンクとクライアントセッション管理は、このバックエンドのオーナーセッションでのみ利用できます。",
  "Reachable at": "接続先",
  "Could not create pairing URL": "ペアリング URL を作成できませんでした",
  "Could not revoke pairing link": "ペアリングリンクを取り消せませんでした",
  "Could not revoke client access": "クライアントアクセスを取り消せませんでした",
  "Could not revoke other clients": "他のクライアントを取り消せませんでした",
  "Could not update admin password": "管理者パスワードを更新できませんでした",
  "Could not disable password authentication": "パスワード認証を無効にできませんでした",
  "Could not update HTTPS": "HTTPS を更新できませんでした",
  "Could not update network access": "ネットワークアクセスを更新できませんでした",

  // Usage and telemetry
  "Collect usage statistics": "使用統計を収集",
  "Data collection": "データ収集",
  "Track tokens, chats, and generating time across all your Club Code use. Data never leaves this machine; turning collection off pauses the counters without clearing them.":
    "Club Code 全体のトークン数、チャット数、生成時間を記録します。データはこのマシンから送信されません。収集をオフにすると、データを消去せずカウンターを一時停止します。",
  "Sidebar provider usage": "サイドバーのプロバイダー使用状況",
  "Show provider usage in sidebar": "サイドバーにプロバイダー使用状況を表示",
  "Usage polling interval": "使用状況のポーリング間隔",
  "Provider usage polling interval": "プロバイダー使用状況のポーリング間隔",
  "Model Pacing": "モデルペーシング",
  "Enable Model Pacing": "モデルペーシングを有効化",
  "Pacing reserve buffer": "ペーシング予備バッファー",
  "Model Pacing reserve buffer": "モデルペーシング予備バッファー",
  "Keep this percentage of each reported allowance unused at reset. The even-spend target is calculated against the remainder.":
    "報告された各使用枠のうち、リセット時に未使用で残す割合です。均等消費目標は残りの使用枠から計算されます。",
  "Token usage by provider and model": "プロバイダー・モデル別のトークン使用量",
  "Tokens by provider and model": "プロバイダー・モデル別トークン",
  "Token efficiency by provider and model": "プロバイダー・モデル別のトークン効率",
  "Token efficiency by model": "モデル別のトークン効率",
  "Provider and model attribution will appear after output tokens are recorded.":
    "出力トークンが記録されると、プロバイダーとモデルの内訳が表示されます。",
  "Cache-reused input": "再利用されたキャッシュ入力",
  "Cache-written input (overhead)": "キャッシュに書き込んだ入力（オーバーヘッド）",
  "Context removed after compaction": "圧縮後に削除されたコンテキスト",
  "Cache reuse and observed compaction will appear when a provider reports them.":
    "プロバイダーから報告された場合、キャッシュ再利用と観測された圧縮が表示されます。",
  "Usage stats are unavailable right now. Reconnect to the server and try again.":
    "現在、使用統計を利用できません。サーバーに再接続してからもう一度お試しください。",
  "Not currently reported by this provider.": "現在このプロバイダーから報告されていません。",

  // Keybindings and profiles
  Keybinding: "キーバインド",
  "Add keybinding": "キーバインドを追加",
  "Cancel new keybinding": "新しいキーバインドをキャンセル",
  "Search keybindings": "キーバインドを検索",
  "No keybindings match your search.": "検索に一致するキーバインドはありません。",
  "Unable to save keybinding": "キーバインドを保存できませんでした",
  "Unable to remove keybinding": "キーバインドを削除できませんでした",
  "Unable to open keybindings file": "キーバインドファイルを開けませんでした",
  "Unable to copy keybindings path": "キーバインドのパスをコピーできませんでした",
  "Settings profiles": "設定プロファイル",
  "Active settings profile": "有効な設定プロファイル",
  "Settings profile name": "設定プロファイル名",
  "Profile name, for example Mobile": "プロファイル名（例: モバイル）",
  "Save current preferences": "現在の環境設定を保存",
  "Switch profile": "プロファイルを切り替え",
  "Reload active settings profile": "有効な設定プロファイルを再読み込み",
  "Select a saved profile to load it immediately. The selected profile stays active after a restart.":
    "保存済みプロファイルを選ぶとすぐに読み込みます。選択したプロファイルは再起動後も有効です。",
  "Profiles are stored only in this browser or desktop client. Saving the same name replaces that local profile.":
    "プロファイルはこのブラウザーまたはデスクトップクライアントにのみ保存されます。同じ名前で保存するとローカルプロファイルを置き換えます。",
  "Saved environments": "保存済み環境",
  "Add saved environment": "保存済み環境を追加",
  "Add environment": "環境を追加",
  "Remove saved environment": "保存済み環境を削除",
  "Remove saved environment?": "保存済み環境を削除しますか？",
  "No remote servers paired": "ペアリング済みリモートサーバーはありません",

  // Archive and recycle bin
  "Archived threads": "アーカイブ済みスレッド",
  "Loading archived threads": "アーカイブ済みスレッドを読み込み中",
  "Could not load archived threads": "アーカイブ済みスレッドを読み込めませんでした",
  "No archived threads": "アーカイブ済みスレッドはありません",
  "Checking connected environments.": "接続済み環境を確認しています。",
  "Archived threads will appear here.": "アーカイブ済みスレッドはここに表示されます。",
  Unarchive: "アーカイブを解除",
  "Failed to unarchive thread": "スレッドのアーカイブを解除できませんでした",
  "Move to Recycle Bin": "ごみ箱へ移動",
  "Empty Recycle Bin": "ごみ箱を空にする",
  "Loading recently deleted threads": "最近削除したスレッドを読み込み中",
  "Could not load recently deleted threads": "最近削除したスレッドを読み込めませんでした",
  "No recently deleted threads": "最近削除したスレッドはありません",
  "Threads moved to the Recycle Bin will appear here.":
    "ごみ箱へ移動したスレッドはここに表示されます。",
  "Delete Forever": "完全に削除",
  "Recycle Bin emptied": "ごみ箱を空にしました",
  "Failed to empty Recycle Bin": "ごみ箱を空にできませんでした",
  "Failed to restore thread": "スレッドを復元できませんでした",
  "Failed to delete thread": "スレッドを削除できませんでした",

  // Diagnostics
  "Runtime Overview": "ランタイム概要",
  "Orchestrator Subprocesses": "オーケストレーターのサブプロセス",
  "Orchestrator Health": "オーケストレーターの健全性",
  "Provider Daemon": "プロバイダーデーモン",
  "Provider Pipeline": "プロバイダーパイプライン",
  "Provider Supervisor": "プロバイダースーパーバイザー",
  "Live Processes": "実行中のプロセス",
  "Resource History": "リソース履歴",
  "Trace Diagnostics": "トレース診断",
  "Latest Failures": "最新の失敗",
  "Most Common Failures": "最も多い失敗",
  "Slowest Spans": "最も遅いスパン",
  "Span Logs": "スパンログ",
  "Top Span Names": "上位のスパン名",
  Process: "プロセス",
  Name: "名前",
  Role: "役割",
  Status: "状態",
  Owner: "所有者",
  Command: "コマンド",
  Type: "種類",
  Memory: "メモリ",
  Current: "現在",
  Average: "平均",
  Peak: "ピーク",
  "CPU Time": "CPU 時間",
  "Max Mem": "最大メモリ",
  Kill: "終了",
  Time: "時刻",
  Level: "レベル",
  Span: "スパン",
  Message: "メッセージ",
  Trace: "トレース",
  Activity: "アクティビティ",
  "Send SIGINT": "SIGINT を送信",
  "Send SIGKILL": "SIGKILL を送信",
  "Copy trace ID": "トレース ID をコピー",
  "Copied trace ID": "トレース ID をコピーしました",
  "Open logs folder": "ログフォルダーを開く",
  "Copy logs folder path": "ログフォルダーのパスをコピー",
  "Logs path copied": "ログのパスをコピーしました",
  "Path copied": "パスをコピーしました",
  "Process already exited": "プロセスはすでに終了しています",
  "No projector cursors found.": "プロジェクターカーソルは見つかりませんでした。",
  "No recent daemon commands.": "最近のデーモンコマンドはありません。",
  "No recent daemon runtime events.": "最近のデーモンランタイムイベントはありません。",
  "No recent orchestration events.": "最近のオーケストレーションイベントはありません。",
  "No supervisor session counts found.": "スーパーバイザーのセッション数は見つかりませんでした。",
};
