/**
 * The appearance bundled with Club Code for operators who opt into The
 * Hexagons background. Activation remains a separate host-owned setting, so
 * shipping a preset never turns the background on for a fresh installation.
 *
 * This document was captured from the operator-approved
 * SeaOfLightsInDarkstaticy appearance on 2026-08-24. Keep it portable:
 * activation and runtime policy belong in
 * their dedicated hint objects, not in the visual settings payload.
 */
export const CLUB_CODE_DEFAULT_HEXAGONS_BACKGROUND_PRESET = {
  kind: "the-hexagons-background",
  formatVersion: 1,
  name: "SeaOfLightsInDarkstaticy",
  target: "generic",
  createdAt: "2026-08-24T07:31:28.596Z",
  settings: {
    schemaVersion: 14,
    quality: "cinematic",
    alignmentMode: "seamless",
    ratioPreset: "silver-major",
    ratioLockOnResize: true,
    displayDiagonalInches: 48,
    tripletLongSpanInches: 0.12,
    manualCssPixelsPerInch: 0,
    tessellationMode: "rhombille",
    material: "glass",
    tileBase: "white",
    customDiamondColorsEnabled: true,
    diamondColorA: "#000000",
    diamondColorB: "#ffffff",
    diamondColorC: "#5c5c5c",
    colorPattern: "facet",
    patternScale: 1,
    patternPhase: 0,
    patternRotation: 0,
    patternMirror: false,
    foregroundIllumination: 0.07,
    gapWidth: 0.075,
    separationAmount: 0.16,
    separationFrequency: 1,
    separationCycle: true,
    emberPulse: false,
    emberIntensity: 0.48,
    emberPattern: "organic",
    emberColorA: "#56005c",
    emberColorB: "#ff006f",
    pistonMode: "off",
    pistonPattern: "individual",
    pistonAmplitude: 0.7,
    pitDepth: 3.5,
    pistonSpeed: 1.12,
    perspectiveStrength: 1.5,
    facetRelief: 0,
    facetReliefSpeed: 0,
    pointerAttractionEnabled: true,
    pointerLightDepthEnabled: true,
    behindLightEnabled: false,
    behindLightType: "point",
    behindLightMotion: "orbit",
    behindLightColor: "#f56200",
    behindWhiteTemperatureKelvin: 1800,
    behindLightIntensity: 24,
    behindLightRadius: 0.13,
    behindLightBeamWidth: 0.25,
    behindLightFanout: 1.1,
    behindLightSpeed: 1.09,
    behindLightFixedX: -0.5,
    behindLightFixedY: 0,
    behindRainbowCycle: true,
    behindRainbowSpeed: 59.78,
    behindPrismStrength: 12,
    behindPrismMode: "neon",
    frontLightEnabled: false,
    frontLightType: "point",
    frontLightMotion: "pointer",
    frontLightColor: "#bb00ff",
    frontWhiteTemperatureKelvin: 12000,
    frontLightIntensity: 0.1,
    frontLightRadius: 0.35,
    frontLightBeamWidth: 1,
    frontLightFanout: 0,
    frontLightSpeed: 0.5,
    frontLightFixedX: -0.5,
    frontLightFixedY: -0.5,
    frontRainbowCycle: false,
    frontRainbowSpeed: 64,
    frontPrismStrength: 0,
    frontPrismMode: "solid",
    gapParticles: "constant",
    meshEnergyTracePistons: true,
    meshEnergyPattern: "piston-groups",
    meshEnergyColor: "#21e6d1",
    meshEnergyRainbowCycle: false,
    meshEnergyRainbowSpeed: 0.02,
    meshEnergyFlowMode: "natural",
    meshEnergyFlowAngle: 234,
    particleCount: 58_900,
    particleSpeed: 4,
    particleSpeedVariation: 1,
    fallingSourceProfile: "club-code",
    fallingEffectKind: "rain",
    fallingMotion: "walk-reverse",
    fallingOpacity: 0.78,
    fallingSpeed: 1,
    fallingDensity: 1,
    fallingScale: 1,
    fallingWind: 0,
    fallingTrail: 8,
    fallingAutoColor: true,
    fallingColor: "#4ade80",
    fallingColorMode: "rainbow-extra",
    fallingColorCycleSpeed: 1,
    fallingJapaneseRatio: 0.45,
    fallingMatrixBaseFontSize: 14,
    fallingReflectionEnabled: true,
    reflectionIntensity: 0.75,
    seed: 1_212_504_115,
  },
  activationHints: {
    backgroundEnabled: false,
    fallingEffectsEnabled: false,
  },
  hostPolicyHints: {
    renderer: "auto",
    reducedMotion: "system",
    continueBackgroundAnimations: false,
  },
} as const;

export const DEFAULT_HEXAGONS_BACKGROUND_PRESET_JSON = JSON.stringify(
  CLUB_CODE_DEFAULT_HEXAGONS_BACKGROUND_PRESET,
);
